/* ══════════════════════════════════════════
   DATA.JS — Citampi Stories Panduan v7
   Sumber: noleep, temannyantai, surgatekno,
           azizpedia, fandom wiki komunitas
══════════════════════════════════════════ */

/* ── CHARACTERS ── */
const chars = [
  /* ═══ HEROINE (bisa dinikahi) ═══ */
  {
    name:"Isma", fullName:"Isma Nur Ainnisa",
    role:"Kasir Indomarket", emoji:"🛒", color:"#00897b",
    heroine:true, canMarry:true, marriageNote:"",
    birthdate:"2 Februari", hobi:"Memasak, baca resep",
    personality:"Alim, sedikit ceroboh, ramah",
    desc:"Kasir Indomarket yang alim dan suka memasak. Walaupun sedikit ceroboh, dia dikenal ramah dan perhatian kepada pelanggan.",
    gifts:{ 8:["Parfum","Kosmetik","Batangan Emas","Siput Emas","Ikan Malaikat","Ikan Bala-bala","Kacamata Emas","Guci Kuno","Piring Kuno","Kalung Mutiara","Parsel Hadiah","Tupperware","Bros Mewah","Batu Rubi","Fosil"], 5:["Coklat","Bunga","Keranjang","Majalah Wanita","Salmon Bakar","Steak Sirloin","Steak T-bone","Ikan Pelangi","Wajan","Cangkir","Sisir","Setrika","Bumbu Masak","Sate","Jengkol Balado","Novel"], 3:[], 1:[] },
    schedule:{
      Senin:   {Pagi:"Indomarket, Area 2",Siang:"Indomarket, Area 2",Sore:"Mebel Jepara, Area 3",Malam:"Samping Gramedia, Area 5"},
      Selasa:  {Pagi:"Depan Masjid, Area 3",Siang:"Dekat Gudeg, Area 2",Sore:"Indomarket, Area 2",Malam:"Indomarket, Area 2"},
      Rabu:    {Pagi:"Indomarket, Area 2",Siang:"Indomarket, Area 2",Sore:"Samping Masjid, Area 3",Malam:"Samping Gramedia, Area 5"},
      Kamis:   {Pagi:"Samping Gramedia, Area 5",Siang:"Distro Gawhul, Area 2",Sore:"Area 2",Malam:"Indomarket, Area 2"},
      Jumat:   {Pagi:"Indomarket, Area 2",Siang:"Indomarket, Area 2",Sore:"Distro Gawhul, Area 2",Malam:"Tukang Gudeg, Area 2"},
      Sabtu:   {Pagi:"Dekat Omegamart, Area 3",Siang:"Depan Joysteak, Area 4",Sore:"—",Malam:"Tukang Gudeg, Area 2"},
      Minggu:  {Pagi:"Dekat Omegamart, Area 3",Siang:"Tukang Gudeg, Area 2",Sore:"Mebel Jepara, Area 3",Malam:"Warung Ganormal, Area 4"},
    }
  },
  {
    name:"Nabila", fullName:"Nabila Resyaliani",
    role:"Kasir Indomarket", emoji:"🛍️", color:"#f472b6",
    heroine:true, canMarry:true, marriageNote:"",
    birthdate:"23 Oktober", hobi:"Nonton drakor, baca novel",
    personality:"Cerewet, pekerja keras, setia",
    desc:"Kasir Indomarket yang cerewet namun pekerja keras. Suka nonton drakor dan sering membicarakan plot favoritnya kepada pelanggan.",
    gifts:{ 8:["Kalung","Jam Tangan","Siput Emas","Ikan Malaikat","Ikan Sapu-sapu","Kalung Mutiara","Kacamata Emas","Guci Kuno","Piring Kuno","Parsel Hadiah","Bros Mewah","Batu Rubi"], 5:["Boneka","Bunga","Coklat","Salmon Bakar","Steak Sirloin","Steak T-bone","Ikan Pelangi","Ikan Diskus","Sisir","Setrika","Buku Catatan","Novel","Susu Kotak"], 3:[], 1:[] },
    schedule:{
      Senin:  {Pagi:"Dekat Gramedia, Area 5",Siang:"Depan Sungai, Area 1",Sore:"Indomarket, Area 2",Malam:"Indomarket, Area 2"},
      Selasa: {Pagi:"Indomarket, Area 2",Siang:"Indomarket, Area 2",Sore:"Distro Gawhul, Area 2",Malam:"Cinemax, Area 4"},
      Rabu:   {Pagi:"Samping Gramedia, Area 5",Siang:"Samping Masjid, Area 3",Sore:"Indomarket, Area 2",Malam:"Indomarket, Area 2"},
      Kamis:  {Pagi:"Indomarket, Area 2",Siang:"Indomarket, Area 2",Sore:"Area 4",Malam:"Depan Mr. Ronald, Area 5"},
      Jumat:  {Pagi:"Tukang Gudeg, Area 2",Siang:"Sungai, Area 1",Sore:"Indomarket, Area 2",Malam:"Indomarket, Area 2"},
      Sabtu:  {Pagi:"Dekat Sungai, Area 1",Siang:"Cinemax, Area 4",Sore:"Distro Gawhul, Area 2",Malam:"Tukang Gudeg, Area 2"},
      Minggu: {Pagi:"Sungai, Area 1",Siang:"Tukang Gudeg, Area 2",Sore:"Cinemax, Area 4",Malam:"Warung Ganormal, Area 4"},
    }
  },
  {
    name:"Indah Putri", fullName:"Indah Putri Savitri",
    role:"Perawat Klinik", emoji:"🌺", color:"#f43f5e",
    heroine:true, canMarry:true, marriageNote:"",
    birthdate:"Tidak diketahui", hobi:"Bidang kesehatan, merawat pasien",
    personality:"Cantik, perhatian, profesional",
    desc:"Perawat klinik yang cantik dan sangat perhatian kepada pasien. Berdedikasi tinggi dalam pekerjaannya.",
    gifts:{ 8:["Batangan Emas","Siput Emas","Ikan Patin","Lobster","Ikan Malaikat","Kalung Mutiara","Kacamata Emas","Guci Kuno","Piring Kuno","Kain","Parsel Hadiah","Gado-gado","Jengkol Balado","Bros Mewah","Batu Rubi"], 5:["Bunga","Parfum","Kosmetik","Kalung","Seblak","Obat Herbal","Steak Sirloin","Steak T-bone","Ikan Ayam-Ayam","Benang Jahit","Jarum Jahit","Brokoli","Bayam","Tomat","Kubis","Kailan","Terong","Sate","Salad Buah","Jengkol"], 3:[], 1:[] },
    schedule:{
      Senin:   {Pagi:"Klinik, Area 2",Siang:"Klinik, Area 2",Sore:"—",Malam:"—"},
      Selasa:  {Pagi:"—",Siang:"—",Sore:"Klinik, Area 2",Malam:"Klinik, Area 2"},
      Rabu:    {Pagi:"Klinik, Area 2",Siang:"Klinik, Area 2",Sore:"—",Malam:"—"},
      Kamis:   {Pagi:"—",Siang:"—",Sore:"Klinik, Area 2",Malam:"Klinik, Area 2"},
      Jumat:   {Pagi:"Klinik, Area 2",Siang:"Klinik, Area 2",Sore:"—",Malam:"—"},
      Sabtu:   {Pagi:"—",Siang:"—",Sore:"—",Malam:"—"},
      Minggu:  {Pagi:"—",Siang:"—",Sore:"—",Malam:"—"},
    }
  },
  {
    name:"Citra Amalia", fullName:"Citra Amalia Putri",
    role:"Kasir Mr. Ronald", emoji:"🌸", color:"#db2777",
    heroine:true, canMarry:true, marriageNote:"",
    birthdate:"Tidak diketahui", hobi:"Baca komik, majalah, mendengarkan musik",
    personality:"Energik, semangat, suka hiburan",
    desc:"Kasir di Mr. Ronald yang energik dan penuh semangat. Selalu update soal musik dan komik terbaru.",
    gifts:{ 8:["Tas Tangan","Batangan Emas","Parfum","Ikan Patin","Ikan Malaikat","Siput Emas","Kacamata Emas","Guci Kuno","Kalung Mutiara","Piring Kuno","Parsel Hadiah","Bros Mewah"], 5:["Headphone","Mie Ayam","Coklat","Steak T-bone","Ikan Pelangi","Majalah Wanita","Ikan Diskus","Kain","Apel","Semangka","Jeruk","Melon","Nangka","Komik","Salad Buah","Burger","Cheeseburger"], 3:[], 1:[] },
    schedule:{
      Senin:  {Pagi:"Mr. Ronald, Area 5",Siang:"Mr. Ronald, Area 5",Sore:"Samping Gramedia, Area 5",Malam:"Cinemax, Area 4"},
      Selasa: {Pagi:"Depan Masjid, Area 3",Siang:"Dekat Gudeg, Area 2",Sore:"Mr. Ronald, Area 5",Malam:"Mr. Ronald, Area 5"},
      Rabu:   {Pagi:"Mr. Ronald, Area 5",Siang:"Mr. Ronald, Area 5",Sore:"Warung Ganormal, Area 4",Malam:"Depan Mr. Ronald, Area 5"},
      Kamis:  {Pagi:"Depan Joysteak, Area 4",Siang:"Distro Gawhul, Area 2",Sore:"Area 5",Malam:"Mr. Ronald, Area 5"},
      Jumat:  {Pagi:"Mr. Ronald, Area 5",Siang:"Mr. Ronald, Area 5",Sore:"Distro Gawhul, Area 2",Malam:"Warung Ganormal, Area 4"},
      Sabtu:  {Pagi:"Dekat Omegamart, Area 3",Siang:"Depan Joysteak, Area 4",Sore:"Atas FFC, Area 5",Malam:"Tukang Gudeg, Area 2"},
      Minggu: {Pagi:"Dekat Omegamart, Area 3",Siang:"Tukang Gudeg, Area 2",Sore:"Cinemax, Area 4",Malam:"Warung Ganormal, Area 4"},
    }
  },
  {
    name:"Jessica", fullName:"Jessica",
    role:"Kasir Mr. Ronald", emoji:"🎨", color:"#7c3aed",
    heroine:true, canMarry:true, marriageNote:"",
    birthdate:"28 Maret", hobi:"Seni, menggambar, jalan-jalan",
    personality:"Aktif, suka seni, ekspresif",
    desc:"Kasir Mr. Ronald yang aktif dan kreatif. Hobi menggambar dan sangat ekspresif dalam mengungkapkan perasaannya.",
    gifts:{ 8:["Bandana","Batangan Emas","Siput Emas","Kalung Mutiara","Buku Seni","Kacamata Emas","Guci Kuno","Piring Kuno","Parsel Hadiah","Bros Mewah","Batu Rubi","Laporan Riset Terbaru"], 5:["Minuman Energi","Coklat","Jam Tangan","Seblak","Sepatu","Ikan Pelangi","Ikan Diskus","Topi","Buku Catatan","Kaleng Cat","Pensil","Novel","Gado-gado","Kuas","Vas Bunga"], 3:[], 1:[] },
    schedule:{
      Senin:  {Pagi:"Dekat Gramedia, Area 5",Siang:"Lapangan, Area 1",Sore:"Mr. Ronald, Area 5",Malam:"Mr. Ronald, Area 5"},
      Selasa: {Pagi:"Mr. Ronald, Area 5",Siang:"Mr. Ronald, Area 5",Sore:"Depan Kolam, Area 4",Malam:"Gramedia, Area 5"},
      Rabu:   {Pagi:"Toko Sepeda, Area 4",Siang:"Samping Gramedia, Area 5",Sore:"Mr. Ronald, Area 5",Malam:"Mr. Ronald, Area 5"},
      Kamis:  {Pagi:"Mr. Ronald, Area 5",Siang:"Mr. Ronald, Area 5",Sore:"Samping Masjid, Area 3",Malam:"Kolam, Area 4"},
      Jumat:  {Pagi:"Gramedia, Area 5",Siang:"Samping Gramedia, Area 5",Sore:"Mr. Ronald, Area 5",Malam:"Mr. Ronald, Area 5"},
      Sabtu:  {Pagi:"Kanan Atas, Area 3",Siang:"Kolam, Area 4",Sore:"Samping Gramedia, Area 5",Malam:"Toko Sepeda, Area 4"},
      Minggu: {Pagi:"Gramedia, Area 5",Siang:"Samping Masjid, Area 3",Sore:"Kanan Atas, Area 1",Malam:"Samping Gramedia, Area 5"},
    }
  },
  {
    name:"Tasya", fullName:"Tasya Wulandari",
    role:"Kasir FFC", emoji:"📚", color:"#0284c7",
    heroine:true, canMarry:true, marriageNote:"",
    birthdate:"21 Februari", hobi:"Membaca, menulis, memasak",
    personality:"Pemalu, pekerja keras, cerdas",
    desc:"Kasir FFC yang pemalu namun cerdas. Gemar membaca buku dari berbagai genre dan sering terlihat di Gramedia.",
    gifts:{ 8:["Kamus","Batangan Emas","Ikan Malaikat","Kura-kura","Cangkir","Siput Emas","Novel","Kalung Mutiara","Kacamata Emas","Guci Kuno","Piring Kuno","Parsel Hadiah","Bros Mewah","Laporan Riset Terbaru","Pen Fountain"], 5:["Biskuit Krim","Coklat","Kopi","Boneka","Kalung","Teka-Teki Silang","Ikan Pelangi","Ikan Diskus","Keranjang","Sisir","Setrika","Brokoli","Bayam","Tomat","Kubis","Kailan","Terong","Buku Seni","Bebek Karet","Toples Kaca"], 3:[], 1:[] },
    schedule:{
      Senin:  {Pagi:"FFC, Area 5",Siang:"FFC, Area 5",Sore:"FFC, Area 5",Malam:"Gramedia, Area 5"},
      Selasa: {Pagi:"FFC, Area 5",Siang:"FFC, Area 5",Sore:"FFC, Area 5",Malam:"Gramedia, Area 5"},
      Rabu:   {Pagi:"FFC, Area 5",Siang:"FFC, Area 5",Sore:"FFC, Area 5",Malam:"Gramedia, Area 5"},
      Kamis:  {Pagi:"FFC, Area 5",Siang:"FFC, Area 5",Sore:"Kolam, Area 4",Malam:"Gramedia, Area 5"},
      Jumat:  {Pagi:"FFC, Area 5",Siang:"FFC, Area 5",Sore:"FFC, Area 5",Malam:"Gramedia, Area 5"},
      Sabtu:  {Pagi:"Ujung Kanan, Area 3",Siang:"Ujung Kanan, Area 3",Sore:"Kolam, Area 4",Malam:"Samping Gramedia, Area 5"},
      Minggu: {Pagi:"Ujung Kanan, Area 3",Siang:"Ujung Kanan, Area 3",Sore:"Kolam, Area 4",Malam:"Samping Gramedia, Area 5"},
    }
  },
  {
    name:"Sarah Angelia", fullName:"Sarah Angelia",
    role:"Kasir Omegamart", emoji:"🌟", color:"#c026d3",
    heroine:true, canMarry:true, marriageNote:"",
    birthdate:"15 Desember", hobi:"Belanja, sosial media, merias diri",
    personality:"Modis, terbuka, suka bergaul",
    desc:"Kasir Omegamart yang modis dan selalu up-to-date soal tren fashion. Sangat aktif di media sosial.",
    gifts:{ 8:["Kalung","Kosmetik","Batangan Emas","Siput Emas","Ikan Malaikat","Ikan Ayam-ayam","Kalung Mutiara","Kacamata Emas","Guci Kuno","Piring Kuno","Parsel Hadiah","Bros Mewah","Batu Rubi"], 5:["Coklat","Bunga","Majalah Wanita","Ikan Pelangi","Ikan Diskus","Salmon Bakar","Steak Sirloin","Steak T-bone","Keranjang","Sisir","Kain","Singkong Goreng","Buku Seni","Gado-gado","Masker","Lipstik"], 3:[], 1:[] },
    schedule:{
      Senin:  {Pagi:"Omegamart, Area 3",Siang:"Omegamart, Area 3",Sore:"Omegamart, Area 3",Malam:"Joysteak, Area 4"},
      Selasa: {Pagi:"Omegamart, Area 3",Siang:"Omegamart, Area 3",Sore:"Distro Gawhul, Area 2",Malam:"Mr. Ronald, Area 5"},
      Rabu:   {Pagi:"Omegamart, Area 3",Siang:"Omegamart, Area 3",Sore:"Omegamart, Area 3",Malam:"Joysteak, Area 4"},
      Kamis:  {Pagi:"Mr. Ronald, Area 5",Siang:"Joysteak, Area 4",Sore:"Distro Gawhul, Area 2",Malam:"Warung Ganormal, Area 4"},
      Jumat:  {Pagi:"Omegamart, Area 3",Siang:"Omegamart, Area 3",Sore:"Omegamart, Area 3",Malam:"Joysteak, Area 4"},
      Sabtu:  {Pagi:"Dekat Omegamart, Area 3",Siang:"Depan Joysteak, Area 4",Sore:"Distro Gawhul, Area 2",Malam:"Joysteak, Area 4"},
      Minggu: {Pagi:"Dekat Omegamart, Area 3",Siang:"Tukang Gudeg, Area 2",Sore:"Cinemax, Area 4",Malam:"Warung Ganormal, Area 4"},
    }
  },
  {
    name:"Windy", fullName:"Windy",
    role:"Kasir Omegamart", emoji:"🏃", color:"#0e7490",
    heroine:true, canMarry:true, marriageNote:"",
    birthdate:"Tidak diketahui", hobi:"Joging, gym, olahraga",
    personality:"Tomboy, energik, kompetitif",
    desc:"Kasir Omegamart yang tomboy dan sangat aktif berolahraga. Selalu terlihat bersemangat dan penuh energi.",
    gifts:{ 8:["Jam Tangan","Sepatu","Ikan Malaikat","Gado-gado","Salad Buah","Batangan Emas","Siput Emas","Kacamata Emas","Guci Kuno","Kalung Mutiara","Parsel Hadiah","Bros Mewah"], 5:["Bandana","Boneka","Komik","Salmon Bakar","Steak Sirloin","Steak T-bone","Ikan Pelangi","Ikan Diskus","Minuman Energi","Keripik Kentang"], 3:[], 1:[] },
    schedule:{
      Senin:  {Pagi:"Dekat Satpam, Area 1",Siang:"Omegamart, Area 3",Sore:"Omegamart, Area 3",Malam:"Joysteak, Area 4"},
      Selasa: {Pagi:"Dekat Satpam, Area 1",Siang:"Omegamart, Area 3",Sore:"Omegamart, Area 3",Malam:"Joysteak, Area 4"},
      Rabu:   {Pagi:"Dekat Satpam, Area 1",Siang:"Omegamart, Area 3",Sore:"Omegamart, Area 3",Malam:"Joysteak, Area 4"},
      Kamis:  {Pagi:"Dekat Satpam, Area 1",Siang:"Omegamart, Area 3",Sore:"Omegamart, Area 3",Malam:"Joysteak, Area 4"},
      Jumat:  {Pagi:"Dekat Satpam, Area 1",Siang:"Omegamart, Area 3",Sore:"Omegamart, Area 3",Malam:"Joysteak, Area 4"},
      Sabtu:  {Pagi:"Dekat Sungai, Area 1",Siang:"Toko Sepeda, Area 4",Sore:"Gym, Area 3",Malam:"Tukang Gudeg, Area 2"},
      Minggu: {Pagi:"Dekat Sungai, Area 1",Siang:"Toko Sepeda, Area 4",Sore:"Gym, Area 3",Malam:"Tukang Gudeg, Area 2"},
    }
  },
  {
    name:"Nissa", fullName:"Nissa",
    role:"Guru SD", emoji:"🍎", color:"#dc2626",
    heroine:true, canMarry:true, marriageNote:"",
    birthdate:"3 November", hobi:"Snack, bermain bersama murid",
    personality:"Ceria, suka anak-anak, lembut",
    desc:"Guru SD yang ceria dan sangat menyayangi murid-muridnya. Selalu membawa camilan dan senang bermain bersama.",
    gifts:{ 8:["Parsel Hadiah","Coklat","Telur Kejutan","Salad Buah","Susu Kotak","Ikan Pelangi","Siput Emas","Cangkir","Batangan Emas","Kacamata Emas","Guci Kuno","Piring Kuno","Kalung Mutiara","Bros Mewah","Batu Rubi","Laporan Riset Terbaru","Fosil","Pen Fountain"], 5:["Es Krim","Cilok","Tahu Bulat","Keripik Kentang","Kalung","Cermin Genggam","Patung Kuno","Ikan Diskus","Pensil","Kuas","Toples Kaca","Bebek Karet","Biskuit Krim","Permen Lolipop"], 3:[], 1:[] },
    schedule:{
      Senin:  {Pagi:"SD, Area 8",Siang:"SD, Area 8",Sore:"Area 6",Malam:"Tidak diketahui"},
      Selasa: {Pagi:"SD, Area 8",Siang:"SD, Area 8",Sore:"Area 6",Malam:"Tidak diketahui"},
      Rabu:   {Pagi:"SD, Area 8",Siang:"SD, Area 8",Sore:"Area 6",Malam:"Tidak diketahui"},
      Kamis:  {Pagi:"SD, Area 8",Siang:"SD, Area 8",Sore:"Area 6",Malam:"Tidak diketahui"},
      Jumat:  {Pagi:"SD, Area 8",Siang:"SD, Area 8",Sore:"Area 6",Malam:"Tidak diketahui"},
      Sabtu:  {Pagi:"Area 6",Siang:"Area 6",Sore:"Area 6",Malam:"Tidak diketahui"},
      Minggu: {Pagi:"Area 6",Siang:"Area 6",Sore:"Area 6",Malam:"Tidak diketahui"},
    }
  },
  {
    name:"Milah Sarmilah", fullName:"Milah Sarmilah",
    role:"Janda / Pedagang", emoji:"💃", color:"#6366f1",
    heroine:true, canMarry:true, marriageNote:"",
    birthdate:"Tidak diketahui", hobi:"Memasak masakan tradisional, berkebun",
    personality:"Polos, lembut, sedikit terbuka",
    desc:"Janda yang ramah dan polos. Ahli memasak masakan tradisional dan hobi berkebun di kampung halamannya.",
    gifts:{ 8:["Kalung","Patung Kuno","Batangan Emas","Ikan Malaikat","Guci Kuno","Kalung Mutiara","Ikan Bala-bala","Kacamata Emas","Piring Kuno","Parsel Hadiah","Jengkol Balado","Pilar Marmer","Bros Mewah","Batu Rubi","Laporan Riset Terbaru","Fosil","Oseng Jantung Pisang","Bolu Pisang","Laptop Rakitan","Album Foto","Walkie Talkie","Lampu Senter","Rol Film","Ikan Ghostfish","Pen Fountain","Gamelan"], 5:["Kosmetik","Cilok","Seblak","Cermin Genggam","Ikan Gurami","Ikan Tawes","Ikan Patin","Tutut","Ikan Nila","Ikan Mujair","Ikan Pelangi","Kacamata","Kipas","Wajan","Radio","Sisir","Bumbu Masak","Nangka","Bakso","Jengkol","Teh Herbal"], 3:[], 1:[] },
    schedule:{
      Senin:   {Pagi:"Pinggir Sungai, Kampung",Siang:"Warung, Kampung",Sore:"Warung, Kampung",Malam:"Rumah, Kampung"},
      Selasa:  {Pagi:"Pinggir Sungai, Kampung",Siang:"Warung, Kampung",Sore:"Warung Bu Noer, Area 3",Malam:"Rumah, Kampung"},
      Rabu:    {Pagi:"Pinggir Sungai, Kampung",Siang:"Warung, Kampung",Sore:"Warung, Kampung",Malam:"Rumah, Kampung"},
      Kamis:   {Pagi:"Pinggir Sungai, Kampung",Siang:"Warung Bu Noer, Area 3",Sore:"Warung, Kampung",Malam:"Rumah, Kampung"},
      Jumat:   {Pagi:"Pinggir Sungai, Kampung",Siang:"Warung, Kampung",Sore:"Warung Bu Noer, Area 3",Malam:"Rumah, Kampung"},
      Sabtu:   {Pagi:"Pinggir Sungai, Kampung",Siang:"Warung, Kampung",Sore:"Warung, Kampung",Malam:"Rumah, Kampung"},
      Minggu:  {Pagi:"Pinggir Sungai, Kampung",Siang:"Warung, Kampung",Sore:"Warung, Kampung",Malam:"Rumah, Kampung"},
    }
  },
  {
    name:"Suciasih", fullName:"Asih / Suciasih",
    role:"Hantu (Kuntilanak)", emoji:"👻", color:"#4338ca",
    heroine:true, canMarry:true,
    marriageNote:"Syarat: Dapatkan Batu Mistis dari HOTLIN HOTEL (beri Ikan Hantu Hitam kepada penjaga hotel)",
    birthdate:"1 Juli", hobi:"Tidak diketahui",
    personality:"Misterius, pendiam, penyendiri",
    desc:"Kuntilanak yang hanya muncul malam hari. Meski menakutkan, dia bisa didekati dan bahkan bisa dinikahi setelah memenuhi syarat khusus.",
    gifts:{ 8:["Paku","Bunga","Sate","Sapu","Batangan Emas","Ikan Black Ghost","Guci Kuno","Piring Kuno","Parsel Hadiah","Ikan Hantu","Ikan Ghostfish","Kemenyan","Jelangkung"], 5:["Kopi","Teh Herbal"], 3:[], 1:[] },
    schedule:{
      Senin:   {Pagi:"—",Siang:"—",Sore:"—",Malam:"Dekat Kos Mpok Lela, Area 1 (jam 22:00+)"},
      Selasa:  {Pagi:"—",Siang:"—",Sore:"—",Malam:"Ena-Ena Hotel, Area 5 (jam 22:00+)"},
      Rabu:    {Pagi:"—",Siang:"—",Sore:"—",Malam:"Pohon Pisang Belakang Rumah, Area 1 (jam 22:00+)"},
      Kamis:   {Pagi:"—",Siang:"—",Sore:"—",Malam:"Kuburan Depan Gudang Pak RT (jam 22:00+)"},
      Jumat:   {Pagi:"—",Siang:"—",Sore:"—",Malam:"Pojok Klinik, Area 2 (jam 22:00+)"},
      Sabtu:   {Pagi:"—",Siang:"—",Sore:"—",Malam:"Dekat Sungai, Area 3 (jam 22:00+)"},
      Minggu:  {Pagi:"—",Siang:"—",Sore:"—",Malam:"Area 6 Bawah Dekat Danau (jam 22:00+)"},
    }
  },
  {
    name:"Teh Imas", fullName:"Teh Imas",
    role:"Istri Mbah Sen / Perawat", emoji:"🌼",color:"#9f1239",
    heroine:true, canMarry:true,
    marriageNote:"Syarat: Mbah Sen harus meninggal terlebih dahulu (event story khusus)",
    birthdate:"Tidak diketahui", hobi:"Memasak, berkebun",
    personality:"Sabar, lembut, penyayang",
    desc:"Istri Mbah Sen yang sabar dan lembut. Bisa didekati secara romantis setelah Mbah Sen meninggal melalui event story khusus.",
    gifts:{ 8:["Kalung","Kosmetik","Parfum","Batangan Emas","Siput Emas","Kacamata Emas","Guci Kuno","Kalung Mutiara","Ikan Pelangi","Piring Kuno","Parsel Hadiah","Bros Mewah"], 5:["Bunga","Boneka","Majalah Wanita","Obat Herbal","Ikan Diskus","Sisir","Bakso","Gado-gado","Sate","Salad Buah","Teh Herbal"], 3:[], 1:[] },
    schedule:{
      Senin:   {Pagi:"Area 2",Siang:"Area 2",Sore:"Area 3",Malam:"Area 2"},
      Selasa:  {Pagi:"Area 2",Siang:"Area 2",Sore:"Area 3",Malam:"Area 2"},
      Rabu:    {Pagi:"Area 2",Siang:"Area 2",Sore:"Area 3",Malam:"Area 2"},
      Kamis:   {Pagi:"Area 2",Siang:"Area 2",Sore:"Area 3",Malam:"Area 2"},
      Jumat:   {Pagi:"Area 2",Siang:"Area 2",Sore:"Area 3",Malam:"Area 2"},
      Sabtu:   {Pagi:"Area 2",Siang:"Area 2",Sore:"Area 3",Malam:"Area 2"},
      Minggu:  {Pagi:"Area 2",Siang:"Area 2",Sore:"Area 3",Malam:"Area 2"},
    }
  },

  /* ═══ WARGA BIASA ═══ */
  {
    name:"Alex", fullName:"Alex",
    role:"Warga / Distro Gawhul", emoji:"👦", color:"#3b82f6",
    heroine:false, canMarry:false, marriageNote:"",
    birthdate:"Tidak diketahui", hobi:"Mode, musik",
    personality:"Santai, modis, suka nongkrong",
    desc:"Anak muda yang bekerja di Distro Gawhul. Suka mode dan musik, sering nongkrong di area Mr. Ronald malam hari.",
    gifts:{ 8:["Jam Tangan","Sepatu","Batangan Emas","Lobster","Siput Emas","Ikan Diskus","Topi","Kacamata Emas","Guci Kuno","Piring Kuno","Kalung Mutiara","Komik","Parsel Hadiah"], 5:["Kalung","Salmon Bakar","Steak Sirloin","Steak T-bone","Ikan Pelangi","Kamus","Benang Jahit","CD","Headphone"], 3:[], 1:[] },
    schedule:{
      Senin:  {Pagi:"Distro Gawhul, Area 2",Siang:"Distro Gawhul, Area 2",Sore:"Distro Gawhul, Area 2",Malam:"Samping Mr. Ronald, Area 5"},
      Selasa: {Pagi:"Distro Gawhul, Area 2",Siang:"Distro Gawhul, Area 2",Sore:"Distro Gawhul, Area 2",Malam:"Samping Mr. Ronald, Area 5"},
      Rabu:   {Pagi:"Distro Gawhul, Area 2",Siang:"Distro Gawhul, Area 2",Sore:"Distro Gawhul, Area 2",Malam:"Samping Mr. Ronald, Area 5"},
      Kamis:  {Pagi:"Distro Gawhul, Area 2",Siang:"Distro Gawhul, Area 2",Sore:"Distro Gawhul, Area 2",Malam:"Samping Mr. Ronald, Area 5"},
      Jumat:  {Pagi:"Distro Gawhul, Area 2",Siang:"Distro Gawhul, Area 2",Sore:"Distro Gawhul, Area 2",Malam:"Samping Mr. Ronald, Area 5"},
      Sabtu:  {Pagi:"Distro Gawhul, Area 2",Siang:"Distro Gawhul, Area 2",Sore:"Distro Gawhul, Area 2",Malam:"Samping Mr. Ronald, Area 5"},
      Minggu: {Pagi:"Distro Gawhul, Area 2",Siang:"Distro Gawhul, Area 2",Sore:"Distro Gawhul, Area 2",Malam:"Samping Mr. Ronald, Area 5"},
    }
  },
  {
    name:"Annissa Lavika", fullName:"Annissa Lavika",
    role:"Warga Citampi", emoji:"👧", color:"#ec4899",
    heroine:false, canMarry:false, marriageNote:"",
    birthdate:"Tidak diketahui", hobi:"Jalan-jalan, hangout",
    personality:"Ceria, ramah, suka bergaul",
    desc:"Warga Citampi yang ceria dan mudah bergaul. Sering terlihat di sekitar sekolah dan masjid.",
    gifts:{ 8:["Coklat","Batangan Emas","Ikan Pelangi","Siput Emas","Kalung Mutiara","Kacamata Emas","Guci Kuno","Piring Kuno","Parsel Hadiah","Telur Kejutan","Salad Buah","Bros Mewah"], 5:["Es Krim","Kalung","Cilok","Tahu Bulat","Patung Kuno","Ikan Diskus","Pensil","Singkong Goreng","Permen Lolipop"], 3:[], 1:[] },
    schedule:{
      Senin:  {Pagi:"Sekitar Sekolah, Area 3",Siang:"Sekitar Sekolah, Area 3",Sore:"Masjid, Area 3",Malam:"Area 3"},
      Selasa: {Pagi:"Sekitar Sekolah, Area 3",Siang:"Sekitar Sekolah, Area 3",Sore:"Masjid, Area 3",Malam:"Area 3"},
      Rabu:   {Pagi:"Sekitar Sekolah, Area 3",Siang:"Sekitar Sekolah, Area 3",Sore:"Masjid, Area 3",Malam:"Area 3"},
      Kamis:  {Pagi:"Sekitar Sekolah, Area 3",Siang:"Sekitar Sekolah, Area 3",Sore:"Masjid, Area 3",Malam:"Area 3"},
      Jumat:  {Pagi:"Sekitar Sekolah, Area 3",Siang:"Sekitar Sekolah, Area 3",Sore:"Masjid, Area 3",Malam:"Area 3"},
      Sabtu:  {Pagi:"Area 3",Siang:"Area 3",Sore:"Area 3",Malam:"Area 3"},
      Minggu: {Pagi:"Area 3",Siang:"Area 3",Sore:"Area 3",Malam:"Area 3"},
    }
  },
  {
    name:"Arpat", fullName:"Arpat",
    role:"Pemilik Warnet", emoji:"🖥️", color:"#8b5cf6",
    heroine:false, canMarry:false, marriageNote:"",
    birthdate:"Tidak diketahui", hobi:"Game online, teknologi",
    personality:"Introvert, geek, cuek",
    desc:"Pemilik warnet yang hobi game dan teknologi. Jarang keluar dari warnetnya.",
    gifts:{ 8:["Jam Tangan","CD","Batangan Emas","Sepatu Kulit","Kacamata Emas","Guci Kuno","Siput Emas","Ikan Diskus","Kalung Mutiara","Piring Kuno","Komik","Parsel Hadiah","Sate","Jengkol Balado"], 5:["Sepatu","Headphone","Radio","Buku Seni","Salmon Bakar","Steak Sirloin","Steak T-bone","Ikan Pelangi","Laptop Rakitan"], 3:[], 1:[] },
    schedule:{
      Senin:  {Pagi:"Warnet, Area 3",Siang:"Warnet, Area 3",Sore:"Warnet, Area 3",Malam:"Warnet, Area 3"},
      Selasa: {Pagi:"Warnet, Area 3",Siang:"Warnet, Area 3",Sore:"Warnet, Area 3",Malam:"Warnet, Area 3"},
      Rabu:   {Pagi:"Warnet, Area 3",Siang:"Warnet, Area 3",Sore:"Warnet, Area 3",Malam:"Warnet, Area 3"},
      Kamis:  {Pagi:"Warnet, Area 3",Siang:"Warnet, Area 3",Sore:"Warnet, Area 3",Malam:"Warnet, Area 3"},
      Jumat:  {Pagi:"Warnet, Area 3",Siang:"Warnet, Area 3",Sore:"Warnet, Area 3",Malam:"Warnet, Area 3"},
      Sabtu:  {Pagi:"Warnet, Area 3",Siang:"Warnet, Area 3",Sore:"Warnet, Area 3",Malam:"Warnet, Area 3"},
      Minggu: {Pagi:"Warnet, Area 3",Siang:"Warnet, Area 3",Sore:"Warnet, Area 3",Malam:"Warnet, Area 3"},
    }
  },
  {
    name:"Bu Noer", fullName:"Bu Noer",
    role:"Pemilik Warung", emoji:"👩", color:"#14b8a6",
    heroine:false, canMarry:false, marriageNote:"",
    birthdate:"Tidak diketahui", hobi:"Memasak, berdagang",
    personality:"Ramah, murah hati, cerewet",
    desc:"Pemilik warung di area 3 yang terkenal ramah. Masakannya lezat dan harganya terjangkau.",
    gifts:{ 8:["Batangan Emas","Ikan Malaikat","Siput Emas","Kacamata Emas","Guci Kuno","Piring Kuno","Tas Tangan","Novel","Parsel Hadiah","Salad Buah"], 5:["Kopi","Kalung","Parfum","Kosmetik","Seblak","Kamus","Ikan Belida","Ikan Pelangi","Jam Weker","Buku Catatan","Pensil","Gado-gado","Jengkol Balado","Teh Botol"], 3:[], 1:[] },
    schedule:{
      Senin:  {Pagi:"Warung, Area 3",Siang:"Warung, Area 3",Sore:"Warung, Area 3",Malam:"Warung, Area 3"},
      Selasa: {Pagi:"Warung, Area 3",Siang:"Warung, Area 3",Sore:"Warung, Area 3",Malam:"Warung, Area 3"},
      Rabu:   {Pagi:"Warung, Area 3",Siang:"Warung, Area 3",Sore:"Warung, Area 3",Malam:"Warung, Area 3"},
      Kamis:  {Pagi:"Warung, Area 3",Siang:"Warung, Area 3",Sore:"Warung, Area 3",Malam:"Warung, Area 3"},
      Jumat:  {Pagi:"Warung, Area 3",Siang:"Warung, Area 3",Sore:"Warung, Area 3",Malam:"Warung, Area 3"},
      Sabtu:  {Pagi:"Warung, Area 3",Siang:"Warung, Area 3",Sore:"Warung, Area 3",Malam:"Warung, Area 3"},
      Minggu: {Pagi:"Warung, Area 3",Siang:"Warung, Area 3",Sore:"Warung, Area 3",Malam:"Warung, Area 3"},
    }
  },
  {
    name:"Bu Tuti", fullName:"Bu Tuti",
    role:"Pemilik Kos", emoji:"🏠", color:"#a16207",
    heroine:false, canMarry:false, marriageNote:"",
    birthdate:"Tidak diketahui", hobi:"Berkebun, menonton TV",
    personality:"Tegas, keibuan, disiplin",
    desc:"Pemilik kos yang tegas namun keibuan. Memastikan semua penghuni kos mematuhi peraturan.",
    gifts:{ 8:["Kalung","Lipstik","Parfum","Kosmetik","Kalung Mutiara","Batangan Emas","Siput Emas","Kacamata Emas","Guci Kuno","Piring Kuno","Buku Seni","Parsel Hadiah"], 5:["Bunga","Majalah Wanita","Jam Tangan","Steak Sirloin","Steak T-bone","Ikan Pelangi","Ikan Diskus","Wajan","Cangkir","Sisir","Setrika","Bumbu Masak","Sate","Salad Buah","Jengkol Balado","Gramaphone"], 3:[], 1:[] },
    schedule:{
      Senin:  {Pagi:"Depan Gudeg, Area 2",Siang:"Depan Kos, Area 4",Sore:"Indomarket, Area 2",Malam:"—"},
      Selasa: {Pagi:"Depan Gudeg, Area 2",Siang:"Depan Kos, Area 4",Sore:"Indomarket, Area 2",Malam:"—"},
      Rabu:   {Pagi:"Depan Gudeg, Area 2",Siang:"Depan Kos, Area 4",Sore:"Indomarket, Area 2",Malam:"—"},
      Kamis:  {Pagi:"Depan Gudeg, Area 2",Siang:"Depan Kos, Area 4",Sore:"Indomarket, Area 2",Malam:"—"},
      Jumat:  {Pagi:"Depan Gudeg, Area 2",Siang:"Depan Kos, Area 4",Sore:"Indomarket, Area 2",Malam:"—"},
      Sabtu:  {Pagi:"Depan Kos, Area 4",Siang:"Depan Kos, Area 4",Sore:"Depan Kos, Area 4",Malam:"—"},
      Minggu: {Pagi:"Depan Kos, Area 4",Siang:"Depan Kos, Area 4",Sore:"Depan Kos, Area 4",Malam:"—"},
    }
  },
  {
    name:"Dokter Dimas", fullName:"Dokter Dimas",
    role:"Dokter Klinik", emoji:"⚕️", color:"#0ea5e9",
    heroine:false, canMarry:false, marriageNote:"",
    birthdate:"Tidak diketahui", hobi:"Membaca jurnal medis, olahraga ringan",
    personality:"Tenang, profesional, disiplin",
    desc:"Dokter klinik yang tenang dan profesional. Sangat disiplin soal jadwal dan pola hidup sehat.",
    gifts:{ 8:["Sepatu","Jam Weker","Batangan Emas","Siput Emas","Ikan Black Ghost","Kacamata Emas","Guci Kuno","Piring Kuno","Kalung Mutiara","Parsel Hadiah"], 5:["Kamus","Teka-Teki Silang","Ikan Pelangi","Ikan Diskus","Brokoli","Bayam","Tomat","Kubis","Kailan","Terong","Semangka","Melon","Jeruk","Nangka","Novel","Buku Seni","Gado-gado","Salad Buah"], 3:[], 1:[] },
    schedule:{
      Senin:  {Pagi:"Indomarket, Area 2",Siang:"Klinik, Area 2",Sore:"Klinik, Area 2",Malam:"Klinik, Area 2"},
      Selasa: {Pagi:"—",Siang:"—",Sore:"Klinik, Area 2",Malam:"Klinik, Area 2"},
      Rabu:   {Pagi:"Klinik, Area 2",Siang:"Klinik, Area 2",Sore:"Klinik, Area 2",Malam:"Klinik, Area 2"},
      Kamis:  {Pagi:"Depan Joysteak, Area 4",Siang:"Distro Gawhul, Area 2",Sore:"Klinik, Area 2",Malam:"Klinik, Area 2"},
      Jumat:  {Pagi:"Klinik, Area 2",Siang:"Klinik, Area 2",Sore:"Klinik, Area 2",Malam:"Klinik, Area 2"},
      Sabtu:  {Pagi:"Klinik, Area 2",Siang:"Klinik, Area 2",Sore:"Klinik, Area 2",Malam:"Klinik, Area 2"},
      Minggu: {Pagi:"Klinik, Area 2",Siang:"Klinik, Area 2",Sore:"Klinik, Area 2",Malam:"Klinik, Area 2"},
    }
  },
  {
    name:"Kak Seno", fullName:"Kak Seno",
    role:"Warga Citampi", emoji:"🧓", color:"#64748b",
    heroine:false, canMarry:false, marriageNote:"",
    birthdate:"Tidak diketahui", hobi:"Membaca, mendengarkan radio",
    personality:"Bijak, pendiam, nostalgia",
    desc:"Warga senior Citampi yang bijaksana. Senang membaca dan mendengarkan radio lagu-lagu lawas.",
    gifts:{ 8:["Jam Tangan","Sepatu","Batangan Emas","Ikan Gabus","Siput Emas","Sepatu Kulit","Kacamata Emas","Guci Kuno","Piring Kuno","Kalung Mutiara","Novel","Parsel Hadiah"], 5:["Kamus","Teka-Teki Silang","Kipas","Ikan Pelangi","Ikan Diskus","Kacamata","Jam Tangan Kulit","Radio","Buku Catatan","Buku Seni","Pensil"], 3:[], 1:[] },
    schedule:{
      Senin:  {Pagi:"Indomarket, Area 2",Siang:"—",Sore:"Depan Warung Bu Noer, Area 3",Malam:"Gramedia, Area 5"},
      Selasa: {Pagi:"Area 2",Siang:"Area 2",Sore:"Area 3",Malam:"Area 5"},
      Rabu:   {Pagi:"Area 2",Siang:"Area 2",Sore:"Area 3",Malam:"Area 5"},
      Kamis:  {Pagi:"Area 2",Siang:"Area 2",Sore:"Area 3",Malam:"Area 5"},
      Jumat:  {Pagi:"Area 2",Siang:"Area 2",Sore:"Area 3",Malam:"Area 5"},
      Sabtu:  {Pagi:"Area 2",Siang:"Area 2",Sore:"Area 3",Malam:"Area 5"},
      Minggu: {Pagi:"Area 2",Siang:"Area 2",Sore:"Area 3",Malam:"Area 5"},
    }
  },
  {
    name:"Lina", fullName:"Lina",
    role:"Anak Kecil", emoji:"🧒", color:"#f59e0b",
    heroine:false, canMarry:false, marriageNote:"",
    birthdate:"Tidak diketahui", hobi:"Bermain, koleksi mainan",
    personality:"Manja, ceria, suka bermain",
    desc:"Anak kecil yang manja dan ceria. Senang bermain dan mengoleksi mainan baru.",
    gifts:{ 8:["Telur Kejutan","Boneka","Kalung","Siput Emas","Kacamata Emas","Guci Kuno","Kalung Mutiara","Ikan Pelangi","Piring Kuno","Cemilan Kekinian","Mainan Kekinian","Lego","Parsel Hadiah","Bebek Karet","Mobil-mobilan"], 5:["Cilok","Seblak","Tahu Bulat","Gorengan","Bunga","Jam Tangan","Sepatu","Kamus","Salmon Bakar","Ikan Diskus","Burger","Komik","Salad Buah","Permen Lolipop"], 3:[], 1:[] },
    schedule:{
      Senin:  {Pagi:"Taman Bermain, Area 1–3",Siang:"Taman Bermain, Area 1–3",Sore:"Area 1–3",Malam:"Rumah"},
      Selasa: {Pagi:"Taman Bermain, Area 1–3",Siang:"Taman Bermain, Area 1–3",Sore:"Area 1–3",Malam:"Rumah"},
      Rabu:   {Pagi:"Taman Bermain, Area 1–3",Siang:"Taman Bermain, Area 1–3",Sore:"Area 1–3",Malam:"Rumah"},
      Kamis:  {Pagi:"Taman Bermain, Area 1–3",Siang:"Taman Bermain, Area 1–3",Sore:"Area 1–3",Malam:"Rumah"},
      Jumat:  {Pagi:"Taman Bermain, Area 1–3",Siang:"Taman Bermain, Area 1–3",Sore:"Area 1–3",Malam:"Rumah"},
      Sabtu:  {Pagi:"Area 1–3",Siang:"Area 1–3",Sore:"Area 1–3",Malam:"Rumah"},
      Minggu: {Pagi:"Area 1–3",Siang:"Area 1–3",Sore:"Area 1–3",Malam:"Rumah"},
    }
  },
  {
    name:"Mbah Sen", fullName:"Mbah Sen",
    role:"Sesepuh Citampi", emoji:"👴", color:"#6b7280",
    heroine:false, canMarry:false,
    marriageNote:"Catatan: Mbah Sen adalah NPC yang memiliki event meninggal. Setelah meninggal, muncul sebagai 'Joko' (hantu versi muda).",
    birthdate:"Tidak diketahui", hobi:"Memancing, mengobrol dengan warga",
    personality:"Bijak, ramah, suka cerita masa lalu",
    desc:"Sesepuh Citampi yang bijaksana dan ramah. Suami Teh Imas. Memiliki event story khusus. Setelah meninggal, arwahnya muncul sebagai Joko.",
    gifts:{ 8:["Parfum","Jam Tangan","Kalung","Kosmetik","Radio","Sepatu","Obat Herbal","Patung Kuno","Batangan Emas","Ikan Piranha","Siput Emas","Ikan Black Ghost","Kalung Mutiara","Kacamata Emas","Guci Kuno","Piring Kuno","Parsel Hadiah","Sate"], 5:["Bunga","Boneka","Bandana","Majalah Wanita","Teka-Teki Silang","Ikan Arwana","Salmon Bakar","Steak Sirloin","Steak T-bone","Ikan Koi","Ikan Diskus","Ikan Pelangi","Jam Tangan Kulit","Sepatu Kulit","Kaleng Cat","Bakso","Jengkol Balado"], 3:[], 1:[] },
    schedule:{
      Senin:  {Pagi:"Area 1",Siang:"Depan Sungai, Area 1",Sore:"Depan Warung Bu Noer, Area 3",Malam:"Samping Pom Bensin, Area 2"},
      Selasa: {Pagi:"Area 1",Siang:"Depan Sungai, Area 1",Sore:"Depan Warung Bu Noer, Area 3",Malam:"Samping Pom Bensin, Area 2"},
      Rabu:   {Pagi:"Area 1",Siang:"Depan Sungai, Area 1",Sore:"Depan Warung Bu Noer, Area 3",Malam:"Samping Pom Bensin, Area 2"},
      Kamis:  {Pagi:"Area 1",Siang:"Depan Sungai, Area 1",Sore:"Depan Warung Bu Noer, Area 3",Malam:"Samping Pom Bensin, Area 2"},
      Jumat:  {Pagi:"Area 1",Siang:"Depan Sungai, Area 1",Sore:"Depan Warung Bu Noer, Area 3",Malam:"Samping Pom Bensin, Area 2"},
      Sabtu:  {Pagi:"Area 1",Siang:"Depan Sungai, Area 1",Sore:"Depan Warung Bu Noer, Area 3",Malam:"Samping Pom Bensin, Area 2"},
      Minggu: {Pagi:"Area 1",Siang:"Depan Sungai, Area 1",Sore:"Depan Warung Bu Noer, Area 3",Malam:"Samping Pom Bensin, Area 2"},
    }
  },
  {
    name:"Mpok Lela", fullName:"Mpok Lela",
    role:"Warga Citampi", emoji:"🌼", color:"#e879f9",
    heroine:false, canMarry:false, marriageNote:"",
    birthdate:"Tidak diketahui", hobi:"Memasak, bersosialisasi",
    personality:"Cerewet, ramah, suka bergosip",
    desc:"Warga Citampi yang cerewet namun ramah. Selalu tahu berita terbaru di kampung.",
    gifts:{ 8:["Kalung","Kosmetik","Batangan Emas","Parfum","Siput Emas","Kalung Mutiara","Kacamata Emas","Guci Kuno","Piring Kuno","Parsel Hadiah","Jengkol Balado"], 5:["Wajan","Jam Tangan","Bunga","Salmon Bakar","Ikan Pelangi","Ikan Diskus","Kipas","Lampu Hias","Setrika","Bumbu Masak","Kain Jahit","Jarum Jahit"], 3:[], 1:[] },
    schedule:{
      Senin:  {Pagi:"Depan Warung Bu Noer, Area 3",Siang:"Depan Klinik, Area 2",Sore:"Indomarket, Area 2",Malam:"Rumah, Area 2"},
      Selasa: {Pagi:"Depan Warung Bu Noer, Area 3",Siang:"Depan Klinik, Area 2",Sore:"Indomarket, Area 2",Malam:"Rumah, Area 2"},
      Rabu:   {Pagi:"Depan Warung Bu Noer, Area 3",Siang:"Depan Klinik, Area 2",Sore:"Indomarket, Area 2",Malam:"Rumah, Area 2"},
      Kamis:  {Pagi:"Depan Warung Bu Noer, Area 3",Siang:"Depan Klinik, Area 2",Sore:"Indomarket, Area 2",Malam:"Rumah, Area 2"},
      Jumat:  {Pagi:"Depan Warung Bu Noer, Area 3",Siang:"Depan Klinik, Area 2",Sore:"Indomarket, Area 2",Malam:"Rumah, Area 2"},
      Sabtu:  {Pagi:"Depan Warung Bu Noer, Area 3",Siang:"Depan Klinik, Area 2",Sore:"Indomarket, Area 2",Malam:"Rumah, Area 2"},
      Minggu: {Pagi:"Depan Warung Bu Noer, Area 3",Siang:"Depan Klinik, Area 2",Sore:"Indomarket, Area 2",Malam:"Rumah, Area 2"},
    }
  },
  {
    name:"Nopandi", fullName:"Nopandi",
    role:"Warga Citampi", emoji:"🧑", color:"#0891b2",
    heroine:false, canMarry:false, marriageNote:"",
    birthdate:"Tidak diketahui", hobi:"Olahraga, nongkrong",
    personality:"Santai, mudah bergaul",
    desc:"Warga Citampi yang santai dan mudah bergaul. Sering terlihat di sekitar klinik dan area makanan.",
    gifts:{ 8:["Jam Tangan","Sepatu","Obat Herbal","Batangan Emas","Siput Emas","Kalung Mutiara","Kacamata Emas","Guci Kuno","Piring Kuno","Parsel Hadiah"], 5:["Kamus","Teka-Teki Silang","Salmon Bakar","Steak Sirloin","Steak T-bone","Ikan Pelangi","Ikan Diskus","Teko","Ayam Kriuk","Komik"], 3:[], 1:[] },
    schedule:{
      Senin:  {Pagi:"Klinik, Area 2",Siang:"Depan Gudeg, Area 2",Sore:"Depan FFC, Area 5",Malam:"Indomarket, Area 2"},
      Selasa: {Pagi:"Klinik, Area 2",Siang:"Klinik, Area 2",Sore:"Area 2",Malam:"Area 2"},
      Rabu:   {Pagi:"Klinik, Area 2",Siang:"Depan Gudeg, Area 2",Sore:"Depan FFC, Area 5",Malam:"Indomarket, Area 2"},
      Kamis:  {Pagi:"Klinik, Area 2",Siang:"Klinik, Area 2",Sore:"Area 2",Malam:"Area 2"},
      Jumat:  {Pagi:"Klinik, Area 2",Siang:"Depan Gudeg, Area 2",Sore:"Depan FFC, Area 5",Malam:"Indomarket, Area 2"},
      Sabtu:  {Pagi:"Area 2",Siang:"Area 2",Sore:"Area 2",Malam:"Area 2"},
      Minggu: {Pagi:"Area 2",Siang:"Area 2",Sore:"Area 2",Malam:"Area 2"},
    }
  },
  {
    name:"Pak Soleh", fullName:"Pak Soleh",
    role:"Kepala Desa", emoji:"🏛️", color:"#15803d",
    heroine:false, canMarry:false, marriageNote:"",
    birthdate:"Tidak diketahui", hobi:"Memancing, membaca berita",
    personality:"Berwibawa, tegas, adil",
    desc:"Kepala Desa Citampi yang berwibawa dan adil. Bertanggung jawab atas kesejahteraan warga desa.",
    gifts:{ 8:["Jam Tangan","Obat Herbal","Batangan Emas","Siput Emas","Ikan Patin","Lobster","Jam Tangan Kulit","Salmon Bakar","Kalung Mutiara","Kacamata Emas","Guci Kuno","Piring Kuno","Parsel Hadiah"], 5:["Gorengan","Teka-Teki Silang","Ikan Malaikat","Ikan Pelangi","Ikan Sidat","Nugget Ayam","Jengkol Balado","Teh Botol"], 3:[], 1:[] },
    schedule:{
      Senin:  {Pagi:"Dekat Toko Pak Tatang, Area 3",Siang:"Balai Desa, Area 3",Sore:"Balai Desa, Area 3",Malam:"Rumah"},
      Selasa: {Pagi:"Dekat Toko Pak Tatang, Area 3",Siang:"Balai Desa, Area 3",Sore:"Balai Desa, Area 3",Malam:"Rumah"},
      Rabu:   {Pagi:"Dekat Toko Pak Tatang, Area 3",Siang:"Balai Desa, Area 3",Sore:"Balai Desa, Area 3",Malam:"Rumah"},
      Kamis:  {Pagi:"Dekat Toko Pak Tatang, Area 3",Siang:"Balai Desa, Area 3",Sore:"Balai Desa, Area 3",Malam:"Rumah"},
      Jumat:  {Pagi:"Dekat Toko Pak Tatang, Area 3",Siang:"Balai Desa, Area 3",Sore:"Balai Desa, Area 3",Malam:"Rumah"},
      Sabtu:  {Pagi:"Area 3",Siang:"Area 3",Sore:"Area 3",Malam:"Rumah"},
      Minggu: {Pagi:"Area 3",Siang:"Area 3",Sore:"Area 3",Malam:"Rumah"},
    }
  },
  {
    name:"Pak Tatang", fullName:"Pak Tatang",
    role:"Pemilik Kios", emoji:"🏪", color:"#b45309",
    heroine:false, canMarry:false, marriageNote:"",
    birthdate:"Tidak diketahui", hobi:"Berdagang, mengobrol dengan pelanggan",
    personality:"Ramah, suka mengobrol, dermawan",
    desc:"Pemilik kios di area 1 yang ramah. Menjual berbagai barang dari pakaian hingga aksesoris. Tokonya buka pagi hingga malam.",
    gifts:{ 8:["Sepatu","Salmon Bakar","Steak Sirloin","Steak T-bone","Sepatu Kulit","Patung Kuno","Batangan Emas","Siput Emas","Obat Herbal","Ikan Black Ghost","Sate","Kalung Mutiara","Kacamata Emas","Guci Kuno","Piring Kuno","Parsel Hadiah"], 5:["Topi","Gorengan","Cilok","Seblak","Ikan Pelangi","Ikan Diskus","Jam Tangan Kulit","Setrika","Jam Weker","Kaleng Cat","Nugget Ayam","Plat Baja","Komik"], 3:[], 1:[] },
    schedule:{
      Senin:  {Pagi:"Toko Pak Tatang, Area 1",Siang:"Toko Pak Tatang, Area 1",Sore:"Toko Pak Tatang, Area 1",Malam:"Toko Pak Tatang, Area 1"},
      Selasa: {Pagi:"Toko Pak Tatang, Area 1",Siang:"Toko Pak Tatang, Area 1",Sore:"Toko Pak Tatang, Area 1",Malam:"Toko Pak Tatang, Area 1"},
      Rabu:   {Pagi:"Toko Pak Tatang, Area 1",Siang:"Toko Pak Tatang, Area 1",Sore:"Toko Pak Tatang, Area 1",Malam:"Toko Pak Tatang, Area 1"},
      Kamis:  {Pagi:"Toko Pak Tatang, Area 1",Siang:"Toko Pak Tatang, Area 1",Sore:"Toko Pak Tatang, Area 1",Malam:"Toko Pak Tatang, Area 1"},
      Jumat:  {Pagi:"Toko Pak Tatang, Area 1",Siang:"Toko Pak Tatang, Area 1",Sore:"Toko Pak Tatang, Area 1",Malam:"Toko Pak Tatang, Area 1"},
      Sabtu:  {Pagi:"Toko Pak Tatang, Area 1",Siang:"Toko Pak Tatang, Area 1",Sore:"Toko Pak Tatang, Area 1",Malam:"Toko Pak Tatang, Area 1"},
      Minggu: {Pagi:"Toko Pak Tatang, Area 1",Siang:"Toko Pak Tatang, Area 1",Sore:"Toko Pak Tatang, Area 1",Malam:"Toko Pak Tatang, Area 1"},
    }
  },
  {
    name:"Pak Tio", fullName:"Pak Tio",
    role:"Satpam Desa", emoji:"🎸", color:"#1d4ed8",
    heroine:false, canMarry:false, marriageNote:"",
    birthdate:"Tidak diketahui", hobi:"Musik, gitar",
    personality:"Serius saat bertugas, santai di luar tugas",
    desc:"Satpam desa yang serius saat bertugas. Di luar tugas, dia hobi bermain gitar.",
    gifts:{ 8:["Jam Tangan","Jam Weker","Batangan Emas","Ikan Belida","Siput Emas","Kacamata Emas","Guci Kuno","Kalung Mutiara","Parsel Hadiah"], 5:["Kopi","Sepatu","Minuman Energi","CD","Teko","Ikan Pelangi","Ikan Diskus","Sepatu Kulit","Obat Nyamuk Bakar","Komik","Jengkol Balado"], 3:[], 1:[] },
    schedule:{
      Senin:  {Pagi:"Pos Satpam, Area 1",Siang:"Pos Satpam, Area 1",Sore:"Pos Satpam, Area 1",Malam:"Pos Satpam, Area 1"},
      Selasa: {Pagi:"Pos Satpam, Area 1",Siang:"Pos Satpam, Area 1",Sore:"Pos Satpam, Area 1",Malam:"Pos Satpam, Area 1"},
      Rabu:   {Pagi:"Pos Satpam, Area 1",Siang:"Pos Satpam, Area 1",Sore:"Pos Satpam, Area 1",Malam:"Pos Satpam, Area 1"},
      Kamis:  {Pagi:"Pos Satpam, Area 1",Siang:"Pos Satpam, Area 1",Sore:"Pos Satpam, Area 1",Malam:"Pos Satpam, Area 1"},
      Jumat:  {Pagi:"Pos Satpam, Area 1",Siang:"Pos Satpam, Area 1",Sore:"Pos Satpam, Area 1",Malam:"Pos Satpam, Area 1"},
      Sabtu:  {Pagi:"Pos Satpam, Area 1",Siang:"Pos Satpam, Area 1",Sore:"Pos Satpam, Area 1",Malam:"Pos Satpam, Area 1"},
      Minggu: {Pagi:"Pos Satpam, Area 1",Siang:"Pos Satpam, Area 1",Sore:"Pos Satpam, Area 1",Malam:"Pos Satpam, Area 1"},
    }
  },
  {
    name:"Rara", fullName:"Rara",
    role:"Anak Kecil", emoji:"🎀", color:"#e11d48",
    heroine:false, canMarry:false, marriageNote:"",
    birthdate:"Tidak diketahui", hobi:"Bermain, mengoleksi boneka",
    personality:"Aktif, manja, suka boneka",
    desc:"Anak kecil yang aktif dan manja. Hobi mengoleksi boneka dan suka bermain di taman.",
    gifts:{ 8:["Telur Kejutan","Boneka","Kalung","Batangan Emas","Siput Emas","Kacamata Emas","Guci Kuno","Kalung Mutiara","Ikan Pelangi","Piring Kuno","Cemilan Kekinian","Mainan Kekinian","Mainan Tradisional","Parsel Hadiah","Bebek Karet","Mobil-mobilan"], 5:["Bunga","Jam Tangan","Cilok","Seblak","Bandana","Tahu Bulat","Gorengan","Sepatu","Kamus","Steak Sirloin","Ikan Diskus","Nugget Ayam","Komik","Salad Buah","Permen Lolipop"], 3:[], 1:[] },
    schedule:{
      Senin:  {Pagi:"Taman Bermain, Area 1–3",Siang:"Taman Bermain, Area 1–3",Sore:"Area 1–3",Malam:"Rumah"},
      Selasa: {Pagi:"Taman Bermain, Area 1–3",Siang:"Taman Bermain, Area 1–3",Sore:"Area 1–3",Malam:"Rumah"},
      Rabu:   {Pagi:"Taman Bermain, Area 1–3",Siang:"Taman Bermain, Area 1–3",Sore:"Area 1–3",Malam:"Rumah"},
      Kamis:  {Pagi:"Taman Bermain, Area 1–3",Siang:"Taman Bermain, Area 1–3",Sore:"Area 1–3",Malam:"Rumah"},
      Jumat:  {Pagi:"Taman Bermain, Area 1–3",Siang:"Taman Bermain, Area 1–3",Sore:"Area 1–3",Malam:"Rumah"},
      Sabtu:  {Pagi:"Area 1–3",Siang:"Area 1–3",Sore:"Area 1–3",Malam:"Rumah"},
      Minggu: {Pagi:"Area 1–3",Siang:"Area 1–3",Sore:"Area 1–3",Malam:"Rumah"},
    }
  },
  {
    name:"Shelli", fullName:"Shelli",
    role:"Anak Kecil", emoji:"🧸", color:"#d97706",
    heroine:false, canMarry:false, marriageNote:"",
    birthdate:"Tidak diketahui", hobi:"Bermain, makan jajanan",
    personality:"Pemalu, lucu, suka jajan",
    desc:"Anak kecil yang pemalu dan lucu. Selalu senang ketika diberi jajanan atau mainan.",
    gifts:{ 8:["Telur Kejutan","Boneka","Kalung","Batangan Emas","Siput Emas","Kacamata Emas","Guci Kuno","Kalung Mutiara","Ikan Pelangi","Piring Kuno","Cemilan Kekinian","Mainan Kekinian","Boneka Kain","Parsel Hadiah","Bebek Karet","Mobil-mobilan"], 5:["Bunga","Jam Tangan","Cilok","Seblak","Tahu Bulat","Gorengan","Sepatu","Kamus","Steak T-bone","Ayam Kriuk","Komik","Ikan Diskus","Salad Buah","Permen Lolipop"], 3:[], 1:[] },
    schedule:{
      Senin:  {Pagi:"Taman Bermain, Area 1–3",Siang:"Taman Bermain, Area 1–3",Sore:"Area 1–3",Malam:"Rumah"},
      Selasa: {Pagi:"Taman Bermain, Area 1–3",Siang:"Taman Bermain, Area 1–3",Sore:"Area 1–3",Malam:"Rumah"},
      Rabu:   {Pagi:"Taman Bermain, Area 1–3",Siang:"Taman Bermain, Area 1–3",Sore:"Area 1–3",Malam:"Rumah"},
      Kamis:  {Pagi:"Taman Bermain, Area 1–3",Siang:"Taman Bermain, Area 1–3",Sore:"Area 1–3",Malam:"Rumah"},
      Jumat:  {Pagi:"Taman Bermain, Area 1–3",Siang:"Taman Bermain, Area 1–3",Sore:"Area 1–3",Malam:"Rumah"},
      Sabtu:  {Pagi:"Area 1–3",Siang:"Area 1–3",Sore:"Area 1–3",Malam:"Rumah"},
      Minggu: {Pagi:"Area 1–3",Siang:"Area 1–3",Sore:"Area 1–3",Malam:"Rumah"},
    }
  },
  {
    name:"Tigor", fullName:"Tigor",
    role:"Pelatih Gym", emoji:"💪", color:"#f97316",
    heroine:false, canMarry:false, marriageNote:"",
    birthdate:"Tidak diketahui", hobi:"Gym, olahraga, diet sehat",
    personality:"Disiplin, semangat, motivatif",
    desc:"Pelatih gym yang disiplin dan selalu memotivasi. Sangat peduli dengan pola hidup sehat.",
    gifts:{ 8:["Sepatu","Jam Tangan","Obat Herbal","Batangan Emas","Siput Emas","Kacamata Emas","Guci Kuno","Kalung Mutiara","Piring Kuno","Parsel Hadiah"], 5:["Bunga","Parfum","Boneka","Steak Sirloin","Majalah Wanita","Ikan Pelangi","Ikan Betok","Ikan Diskus","Teko","Perangkap Tikus","Bayam","Novel","Gado-gado","Salad Buah","Minuman Energi"], 3:[], 1:[] },
    schedule:{
      Senin:  {Pagi:"Gym, Area 3",Siang:"Gym, Area 3",Sore:"Gym, Area 3",Malam:"Gym, Area 3"},
      Selasa: {Pagi:"Gym, Area 3",Siang:"Gym, Area 3",Sore:"Gym, Area 3",Malam:"Gym, Area 3"},
      Rabu:   {Pagi:"Gym, Area 3",Siang:"Gym, Area 3",Sore:"Gym, Area 3",Malam:"Gym, Area 3"},
      Kamis:  {Pagi:"Gym, Area 3",Siang:"Gym, Area 3",Sore:"Gym, Area 3",Malam:"Gym, Area 3"},
      Jumat:  {Pagi:"Gym, Area 3",Siang:"Gym, Area 3",Sore:"Gym, Area 3",Malam:"Gym, Area 3"},
      Sabtu:  {Pagi:"Gym, Area 3",Siang:"Gym, Area 3",Sore:"Gym, Area 3",Malam:"Gym, Area 3"},
      Minggu: {Pagi:"Gym, Area 3",Siang:"Gym, Area 3",Sore:"Gym, Area 3",Malam:"Gym, Area 3"},
    }
  },
  {
    name:"Ustadz Didi", fullName:"Ustadz Didi",
    role:"Ustadz", emoji:"🕌", color:"#166534",
    heroine:false, canMarry:false, marriageNote:"",
    birthdate:"Tidak diketahui", hobi:"Mengaji, mengajar agama",
    personality:"Religius, sabar, bijaksana",
    desc:"Ustadz kampung yang sabar dan bijaksana. Sering memberikan nasihat kepada warga.",
    gifts:{ 8:["Jam Tangan","Sepatu","Batangan Emas","Siput Emas","Kacamata Emas","Guci Kuno","Kalung Mutiara","Parsel Hadiah"], 5:["Kamus","Teka-Teki Silang","Ikan Pelangi","Teko","Gado-gado","Bakso","Salad Buah","Jengkol Balado","Teh Botol"], 3:[], 1:[] },
    schedule:{
      Senin:  {Pagi:"Masjid, Area 3",Siang:"Mebel Jepara, Area 3",Sore:"Masjid, Area 3",Malam:"Masjid, Area 3"},
      Selasa: {Pagi:"Masjid, Area 3",Siang:"Mebel Jepara, Area 3",Sore:"Masjid, Area 3",Malam:"Masjid, Area 3"},
      Rabu:   {Pagi:"Masjid, Area 3",Siang:"Mebel Jepara, Area 3",Sore:"Masjid, Area 3",Malam:"Masjid, Area 3"},
      Kamis:  {Pagi:"Masjid, Area 3",Siang:"Mebel Jepara, Area 3",Sore:"Masjid, Area 3",Malam:"Masjid, Area 3"},
      Jumat:  {Pagi:"Masjid, Area 3",Siang:"Mebel Jepara, Area 3",Sore:"Masjid, Area 3",Malam:"Masjid, Area 3"},
      Sabtu:  {Pagi:"Masjid, Area 3",Siang:"Masjid, Area 3",Sore:"Masjid, Area 3",Malam:"Masjid, Area 3"},
      Minggu: {Pagi:"Masjid, Area 3",Siang:"Masjid, Area 3",Sore:"Masjid, Area 3",Malam:"Masjid, Area 3"},
    }
  },

  /* ═══ NPC QUEST (tidak bisa dinikahi) ═══ */
  {
    name:"Julia", fullName:"Julia Frederica Mangunkarto",
    role:"Anak Tuan Tanah (NPC Quest)", emoji:"🎩", color:"#854d0e",
    heroine:false, canMarry:false,
    marriageNote:"Julia TIDAK bisa dinikahi. Hanya bisa mendapat max 5 hati untuk keperluan quest.",
    birthdate:"Tidak diketahui", hobi:"Tidak diketahui",
    personality:"Anggun, misterius",
    desc:"Anak Pak Baskoro, tuan tanah kaya. Muncul setelah menikah atau Mbah Sen meninggal. Lokasi di area 6, malam hari. Tidak bisa dinikahi — hanya untuk quest.",
    gifts:{ 8:["Parsel Hadiah Istimewa","Patung Kuno","Tas Tangan","Siput Emas","Batangan Emas"], 5:["Novel","Ikan Arwana","Fosil"], 3:[], 1:[] },
    schedule:{
      Senin:  {Pagi:"—",Siang:"—",Sore:"—",Malam:"Area 6, random (Balai Desa/Petshop/Bengkel)"},
      Selasa: {Pagi:"—",Siang:"—",Sore:"—",Malam:"Area 6, random"},
      Rabu:   {Pagi:"—",Siang:"—",Sore:"—",Malam:"Area 6, random"},
      Kamis:  {Pagi:"—",Siang:"—",Sore:"—",Malam:"Area 6, random"},
      Jumat:  {Pagi:"—",Siang:"—",Sore:"—",Malam:"Area 6, random"},
      Sabtu:  {Pagi:"—",Siang:"—",Sore:"—",Malam:"Area 6, random"},
      Minggu: {Pagi:"—",Siang:"—",Sore:"—",Malam:"Area 6, random"},
    }
  },
  {
    name:"Joko", fullName:"Joko / Hantu Mbah Sen",
    role:"Hantu Mbah Sen (NPC Quest)", emoji:"👻", color:"#44403c",
    heroine:false, canMarry:false,
    marriageNote:"Joko adalah arwah Mbah Sen versi muda. Tidak bisa dinikahi. Muncul setelah Mbah Sen meninggal.",
    birthdate:"Tidak diketahui", hobi:"Tidak diketahui",
    personality:"Misterius, penasaran",
    desc:"Arwah Mbah Sen yang muncul sebagai pemuda tampan (Djoko Seno) setelah Mbah Sen meninggal. Muncul malam hari jam 22:00. Lokasi random tergantung jumlah hati.",
    gifts:{ 8:["Parsel Hadiah","Batangan Emas","Siput Emas","Ikan Black Ghost","Guci Kuno","Piring Kuno"], 5:["Kopi","Sate","Teh Herbal","Kemenyan"], 3:[], 1:[] },
    schedule:{
      Senin:  {Pagi:"—",Siang:"—",Sore:"—",Malam:"Area 1–3 / Area 6 random (jam 22:00+)"},
      Selasa: {Pagi:"—",Siang:"—",Sore:"—",Malam:"Area 1–3 / Area 6 random (jam 22:00+)"},
      Rabu:   {Pagi:"—",Siang:"—",Sore:"—",Malam:"Area 1–3 / Area 6 random (jam 22:00+)"},
      Kamis:  {Pagi:"—",Siang:"—",Sore:"—",Malam:"Area 1–3 / Area 6 random (jam 22:00+)"},
      Jumat:  {Pagi:"—",Siang:"—",Sore:"—",Malam:"Area 1–3 / Area 6 random (jam 22:00+)"},
      Sabtu:  {Pagi:"—",Siang:"—",Sore:"—",Malam:"Area 1–3 / Area 6 random (jam 22:00+)"},
      Minggu: {Pagi:"—",Siang:"—",Sore:"—",Malam:"Area 1–3 / Area 6 random (jam 22:00+)"},
    }
  },
];

/* ── ITEMS ── */
const items = [
  // A
  {name:"Air Doa",cat:"Crafting Khusus",how:"Meja Produksi: Angelfish + Cangkir + Kuas",tip:"Digunakan untuk quest Asih/Suciasih"},
  {name:"Album Foto",cat:"Barang Unik",how:"Didapat dari mulung atau toko tertentu",tip:"Salah satu hadiah Milah +8"},
  {name:"Apel",cat:"Buah",how:"Tanam dari Benih Apel atau beli di pasar",tip:""},
  {name:"Ayam Kriuk",cat:"Makanan",how:"Beli di FFC area 5 atau masak sendiri",tip:""},
  // B
  {name:"Baju Sobek",cat:"Pakaian",how:"Mulung",tip:"Barang mulung, tidak berguna untuk hadiah"},
  {name:"Bakso",cat:"Makanan",how:"Beli di gerobak bakso area 2 atau masak",tip:""},
  {name:"Bambu",cat:"Material",how:"Mancing di area 6 atau beli di Black Market",tip:"Digunakan untuk berbagai crafting"},
  {name:"Bandana",availDays:["Selasa", "Jumat"],cat:"Pakaian",how:"Beli di toko Pak Tatang (Selasa, Jumat)",tip:""},
  {name:"Batang Logam",cat:"Material",how:"Tungku Pelebur: Serpihan Logam + Briket Arang",tip:""},
  {name:"Batangan Emas",cat:"Berharga",how:"Mulung (langka)",tip:"Disukai SEMUA karakter sebagai hadiah +8"},
  {name:"Batu",cat:"Material",how:"Mancing di kolam area 4 atau mulung",tip:""},
  {name:"Batu Bulan",cat:"Crafting Khusus",how:"Tungku Pelebur: Batu + Kerikil Warna-warni + Kristal Warna-warni",tip:"Quest Asih"},
  {name:"Batu Hias",cat:"Material",how:"Mulung",tip:""},
  {name:"Batu Marmer",cat:"Material",how:"Mulung di Sungai Bojong Lima atau dari Pesulap Pink",tip:""},
  {name:"Batu Mistis",cat:"Item Quest",how:"Dari HOTLIN HOTEL (beri Ikan Hantu Hitam kepada penjaga hotel)",tip:"Syarat untuk menikahi Suciasih"},
  {name:"Batu Nisan",cat:"Crafting Khusus",how:"Meja Produksi: Batu Marmer + Batu Hias + Kerikil Warna-warni",tip:"Quest Asih/Joko"},
  {name:"Batu Rubi",cat:"Perhiasan",how:"Mulung di area kampus",tip:""},
  {name:"Batok Kelapa",cat:"Material",how:"Mancing di Sungai Bojong Lima area 6",tip:""},
  {name:"Bayam",cat:"Sayuran",how:"Tanam atau beli di Omegamart",tip:""},
  {name:"Bekas Apel",cat:"Material",how:"Mulung",tip:"Gunakan di Media Pembenihan untuk dapat Benih Apel"},
  {name:"Benang Jahit",cat:"Kerajinan",how:"Beli di toko kerajinan atau tukar di Abu Gosok",tip:""},
  {name:"Benih Apel",cat:"Benih",how:"Media Pembenihan: Bekas Apel",tip:""},
  {name:"Benih Random",cat:"Benih",how:"Media Pembenihan: Ranting Daun",tip:"Hasilnya acak"},
  {name:"Besi Tua",cat:"Material",how:"Mancing di selokan area 2 atau mulung",tip:""},
  {name:"Biskuit Krim",cat:"Makanan",how:"Beli di Omegamart area 3",tip:""},
  {name:"Bola Api",cat:"Crafting Khusus",how:"Meja Produksi: Rotan x2 + Tumpukan Jerami + Thinner",tip:"Quest Asih"},
  {name:"Bola Karet",cat:"Material",how:"Meja Produksi: Karet Gelang x2 + Pelumas",tip:""},
  {name:"Bolu Pisang",cat:"Makanan",how:"Masak sendiri",tip:"Salah satu hadiah Milah +8"},
  {name:"Boneka",availDays:["Senin", "Kamis"],cat:"Mainan",how:"Beli di toko Pak Tatang (Senin, Kamis)",tip:""},
  {name:"Boneka Kain",cat:"Mainan",how:"Meja Produksi: Serpihan Serat + Kain + Benang Jahit",tip:""},
  {name:"Botol Beling",cat:"Material",how:"Mulung",tip:"Bahan Tungku Pelebur untuk Kaca"},
  {name:"Botol Saus",cat:"Material",how:"Mulung",tip:""},
  {name:"Briket Arang",cat:"Material",how:"Tungku Pelebur atau mulung",tip:"Bahan dasar berbagai smelting"},
  {name:"Brokoli",cat:"Sayuran",how:"Tanam atau beli di Omegamart",tip:""},
  {name:"Bros Mewah",cat:"Perhiasan",how:"Beli di toko Pak Tatang",tip:"Disukai banyak heroine sebagai hadiah +8"},
  {name:"Buah Melon",cat:"Buah",how:"Tanam atau beli di pasar",tip:""},
  {name:"Bunga",cat:"Lainnya",how:"Beli di toko Pak Tatang",tip:""},
  {name:"Buku Catatan",cat:"Alat Tulis",how:"Beli di toko alat tulis area 3",tip:""},
  {name:"Buku Seni",cat:"Buku",how:"Beli di Gramedia area 5",tip:""},
  {name:"Bumbu Masak",cat:"Makanan",how:"Beli di Omegamart atau Indomarket",tip:""},
  {name:"Burger",cat:"Makanan",how:"Beli di Mr. Ronald area 5",tip:""},
  // C
  {name:"Cangkir",cat:"Perabotan",how:"Mulung atau beli",tip:"Juga digunakan untuk crafting Air Doa"},
  {name:"Cat",cat:"Material",how:"Beli di Toko Bangunan area 2",tip:""},
  {name:"CD",cat:"Elektronik",how:"Beli di toko Pak Tatang",tip:""},
  {name:"Cemilan Kekinian",cat:"Makanan",how:"Beli di Omegamart atau Indomarket",tip:""},
  {name:"Cermin Genggam",cat:"Kecantikan",how:"Beli di toko atau mulung",tip:""},
  {name:"Cheeseburger",cat:"Makanan",how:"Beli di Mr. Ronald area 5",tip:""},
  {name:"Cilok",cat:"Makanan",how:"Beli di Warung Ganormal area 4 atau gerobak area 2",tip:""},
  {name:"Cincin Nikah",cat:"Perhiasan",how:"Beli di toko Pak Tatang",tip:"Diperlukan untuk proses pernikahan"},
  {name:"Coklat",availDays:["Rabu", "Sabtu"],cat:"Makanan",how:"Beli di toko Pak Tatang (Rabu, Sabtu)",tip:""},
  {name:"Colokan",cat:"Elektronik",how:"Mulung",tip:""},
  // D
  {name:"Dinamo",cat:"Material",how:"Meja Produksi Lv.2: Kabel + Kawat + Gir Mesin + Plat Baja + Pelumas",tip:""},
  // E
  {name:"Eceng Gondok",cat:"Tanaman",how:"Mancing di Sungai Bojong Lima area 6",tip:"Digunakan untuk Teh Herbal"},
  {name:"Es Krim",cat:"Makanan",how:"Beli di Indomarket, Omegamart, atau FFC",tip:""},
  // F
  {name:"Fosil",cat:"Barang Kuno",how:"Mulung (langka)",tip:"Disukai beberapa heroine sebagai hadiah +8"},
  // G
  {name:"Gado-gado",cat:"Makanan",how:"Masak sendiri",tip:""},
  {name:"Gamelan",cat:"Crafting Khusus",how:"Meja Produksi: Batang Logam + Kayu Gelondong x2 + Kristal Warna-warni",tip:"Salah satu hadiah Milah +8"},
  {name:"Garpu",cat:"Perabotan",how:"Mulung",tip:""},
  {name:"Getah Pohon",cat:"Material",how:"Meja Produksi: Ranting Daun x2 atau 1 Nangka",tip:"Bahan Tube Lem"},
  {name:"Gir Mesin",cat:"Material",how:"Dari kucing atau Black Market area 6",tip:""},
  {name:"Gorengan",cat:"Makanan",how:"Beli di Warung Ganormal area 4 atau masak",tip:""},
  {name:"Gramaphone",cat:"Perabotan",how:"Dari Bu Tuti",tip:""},
  {name:"Grilled Fish",cat:"Makanan",how:"Beli di Joysteak area 4",tip:""},
  {name:"Guci Kuno",cat:"Barang Kuno",how:"Mulung",tip:"Disukai SEMUA karakter"},
  // H
  {name:"Headphone",cat:"Elektronik",how:"Mulung (keberuntungan tinggi)",tip:""},
  // I
  {name:"Ikan Arwana",cat:"Ikan",how:"Mancing di area danau khusus",tip:"Luck 3 — langka"},
  {name:"Ikan Ayam-Ayam",cat:"Ikan",how:"Mancing di sungai",tip:"Luck 4 — sangat langka"},
  {name:"Ikan Bala-bala",cat:"Ikan",how:"Mancing di sungai",tip:"Luck 2 — cukup langka"},
  {name:"Ikan Belida",cat:"Ikan",how:"Mancing di sungai (siang-sore)",tip:"Luck 2"},
  {name:"Ikan Betok",cat:"Ikan",how:"Mancing di kolam area 3",tip:"Luck 1 — umum"},
  {name:"Ikan Black Ghost",cat:"Ikan",how:"Mancing di kolam malam hari",tip:"Luck 3 — langka, hanya malam"},
  {name:"Ikan Cupang",cat:"Ikan",how:"Mancing di kolam depan masjid",tip:"Luck 2"},
  {name:"Ikan Diskus",cat:"Ikan",how:"Mancing di kolam area 3",tip:"Luck 1 — umum, disukai banyak karakter"},
  {name:"Ikan Gabus",cat:"Ikan",how:"Mancing di selokan",tip:"Luck 2"},
  {name:"Ikan Ghostfish",cat:"Ikan",how:"Mancing tengah malam (sangat langka)",tip:"Luck 4 — hadiah +8 Milah & Suciasih"},
  {name:"Ikan Gurami",cat:"Ikan",how:"Mancing di kolam",tip:"Luck 1 — umum"},
  {name:"Ikan Hantu",cat:"Ikan",how:"Mancing malam hari di area hantu",tip:""},
  {name:"Ikan Hantu Hitam",cat:"Ikan Quest",how:"Mancing di area khusus malam hari",tip:"Digunakan untuk mendapatkan Batu Mistis (quest Asih)"},
  {name:"Ikan Koi",cat:"Ikan",how:"Mancing di kolam area 3",tip:"Luck 2"},
  {name:"Ikan Lohan",cat:"Ikan",how:"Mancing di danau",tip:"Luck 3 — langka"},
  {name:"Ikan Malaikat",cat:"Ikan",how:"Mancing di kolam area 3",tip:"Luck 2 — favorit +8 banyak heroine!"},
  {name:"Ikan Mas",cat:"Ikan",how:"Mancing di sungai (kapan saja)",tip:"Luck 0 — sangat umum"},
  {name:"Ikan Mas Koki",cat:"Ikan",how:"Mancing di danau",tip:"Luck 2"},
  {name:"Ikan Mujair",cat:"Ikan",how:"Mancing di danau atau sungai",tip:"Luck 1 — umum"},
  {name:"Ikan Naga",cat:"Ikan",how:"Mancing di Sungai Bojong Lima area 6",tip:"Luck 4 — sangat langka"},
  {name:"Ikan Nila",cat:"Ikan",how:"Mancing di sungai",tip:"Luck 0 — sangat umum"},
  {name:"Ikan Patin",cat:"Ikan",how:"Mancing di sungai area 2",tip:"Luck 1"},
  {name:"Ikan Pelangi",cat:"Ikan",how:"Mancing di kolam",tip:"Luck 1 — disukai HAMPIR SEMUA karakter sebagai +5!"},
  {name:"Ikan Piranha",cat:"Ikan",how:"Mancing di area khusus",tip:"Luck 2 — aktif sore/malam"},
  {name:"Ikan Sapu-sapu",cat:"Ikan",how:"Mancing di selokan area 2",tip:"Luck 1"},
  {name:"Ikan Sidat",cat:"Ikan",how:"Mancing di sungai malam hari",tip:"Luck 2"},
  {name:"Ikan Tawes",cat:"Ikan",how:"Mancing di sungai",tip:"Luck 0 — sangat umum"},
  // J
  {name:"Jam Tangan",availDays:["Selasa"],cat:"Aksesoris",how:"Beli di toko Pak Tatang (Selasa)",tip:""},
  {name:"Jam Tangan Kulit",cat:"Aksesoris",how:"Mulung",tip:""},
  {name:"Jam Weker",cat:"Perabotan",how:"Mulung",tip:""},
  {name:"Jantung Pisang",cat:"Bahan Masak",how:"Dari pohon pisang atau mulung",tip:"Bahan Oseng Jantung Pisang dan Kembang Tujuh Rupa"},
  {name:"Jarum Jahit",cat:"Kerajinan",how:"Beli di toko kerajinan",tip:""},
  {name:"Jelangkung",cat:"Crafting Khusus",how:"Meja Produksi: Bambu + Rotan x2 + Batok Kelapa",tip:"Quest Asih/Joko"},
  {name:"Jengkol",cat:"Makanan",how:"Beli di pasar atau mulung",tip:""},
  {name:"Jengkol Balado",cat:"Makanan",how:"Masak sendiri",tip:""},
  {name:"Jeruk",cat:"Buah",how:"Tanam atau beli di pasar",tip:""},
  // K
  {name:"Kabel",cat:"Material",how:"Meja Produksi atau mulung",tip:"Bahan Dinamo"},
  {name:"Kaca",cat:"Material",how:"Tungku Pelebur: Botol Beling + Pasir",tip:""},
  {name:"Kacamata",cat:"Aksesoris",how:"Mulung",tip:""},
  {name:"Kacamata Emas",cat:"Berharga",how:"Mulung (langka)",tip:"Disukai SEMUA karakter sebagai +8"},
  {name:"Kacamata Renang",cat:"Aksesoris",how:"Mulung",tip:""},
  {name:"Kain",cat:"Kerajinan",how:"Beli di toko kerajinan",tip:""},
  {name:"Kain Jarik",cat:"Kain Tradisional",how:"Mancing harta karun Sungai Bojong Lima",tip:""},
  {name:"Kain Perca",cat:"Kerajinan",how:"Meja Produksi",tip:""},
  {name:"Kailan",cat:"Sayuran",how:"Tanam atau beli di Omegamart",tip:""},
  {name:"Kaleng Cat",cat:"Material",how:"Mulung",tip:""},
  {name:"Kalung",availDays:["Senin", "Kamis"],cat:"Perhiasan",how:"Beli di toko Pak Tatang (Senin, Kamis)",tip:""},
  {name:"Kalung Mutiara",availDays:["Selasa", "Jumat"],cat:"Perhiasan",how:"Beli di toko Pak Tatang (Selasa, Jumat)",tip:"Disukai banyak karakter sebagai +8"},
  {name:"Kamus",cat:"Buku",how:"Beli di Gramedia area 5",tip:""},
  {name:"Kaos Kaki",availDays:["Senin", "Kamis"],cat:"Pakaian",how:"Beli di toko Pak Tatang",tip:""},
  {name:"Karet Gelang",cat:"Material",how:"Mancing di danau area 6",tip:"Bahan Bola Karet"},
  {name:"Kartu Remi",cat:"Mainan",how:"Mulung",tip:""},
  {name:"Katapel",cat:"Mainan",how:"Meja Produksi",tip:""},
  {name:"Kawat",cat:"Material",how:"Meja Produksi atau mulung",tip:""},
  {name:"Kayu Gelondong",cat:"Material",how:"Mancing area 6 atau Black Market",tip:"Bahan berbagai crafting"},
  {name:"Kayu Kering",cat:"Material",how:"Meja Produksi: Ranting Daun",tip:""},
  {name:"Kayu Manis",cat:"Rempah",how:"Mancing harta karun Sungai Bojong Lima",tip:"Bahan Teh Herbal & Kemenyan"},
  {name:"Kemeja",availDays:["Rabu", "Sabtu"],cat:"Pakaian",how:"Beli di toko Pak Tatang",tip:""},
  {name:"Kemenyan",cat:"Crafting Khusus",how:"Tungku Pelebur: Briket Arang + Kayu Manis + Serpihan Serat + Getah Pohon",tip:"Hadiah Suciasih +8 & Joko +5"},
  {name:"Kembang Tujuh Rupa",cat:"Crafting Khusus",how:"Meja Produksi: Bunga x3 + Jantung Pisang",tip:"Quest Asih"},
  {name:"Keranjang",cat:"Perabotan",how:"Meja Produksi: Serpihan Serat + Ranting",tip:""},
  {name:"Kerikil Warna-warni",cat:"Material",how:"Mulung atau mancing area 6",tip:"Bahan Batu Bulan & Batu Nisan"},
  {name:"Keripik Kentang",cat:"Makanan",how:"Beli di Omegamart area 3",tip:""},
  {name:"Kipas",cat:"Perabotan",how:"Mulung",tip:""},
  {name:"Kipas Angin",cat:"Perabotan",how:"Mulung",tip:""},
  {name:"Komik",cat:"Buku",how:"Beli di Gramedia area 5",tip:""},
  {name:"Kopi",cat:"Minuman",how:"Beli di warung atau masak sendiri",tip:""},
  {name:"Kosmetik",availDays:["Senin", "Rabu", "Jumat"],cat:"Kecantikan",how:"Beli di toko Pak Tatang",tip:""},
  {name:"Kotak Musik",cat:"Perabotan",how:"Mulung",tip:""},
  {name:"Kristal Warna-warni",cat:"Material",how:"Mancing harta karun Sungai Bojong Lima",tip:"Bahan Batu Bulan & Gamelan"},
  {name:"Kuas",cat:"Alat Tulis",how:"Beli di toko alat tulis area 3",tip:"Juga bahan crafting Air Doa"},
  {name:"Kubis",cat:"Sayuran",how:"Tanam atau beli di Omegamart",tip:""},
  {name:"Kunci Inggris",cat:"Peralatan",how:"Mulung",tip:""},
  {name:"Kura-kura",cat:"Hewan",how:"Mancing di pantai atau area khusus",tip:"Luck 3"},
  // L
  {name:"Lakban",cat:"Material",how:"Meja Produksi",tip:""},
  {name:"Lampu Bohlam",cat:"Perabotan",how:"Mulung",tip:""},
  {name:"Lampu Hias",cat:"Perabotan",how:"Mulung atau beli",tip:""},
  {name:"Lampu Minyak",cat:"Crafting Khusus",how:"Tungku Pelebur: Plat Baja + Batok Kelapa + Pipa Logam + Kaca",tip:"Quest Asih"},
  {name:"Lampu Senter",cat:"Perabotan",how:"Mulung atau beli",tip:"Salah satu hadiah Milah +8"},
  {name:"Laptop Rakitan",cat:"Elektronik",how:"Crafting atau dari toko tertentu",tip:"Salah satu hadiah Milah +8 & Arpat +5"},
  {name:"Laporan Riset Terbaru",cat:"Buku",how:"Mulung di area kampus atau toko tertentu",tip:"Hadiah +8 Milah, Jessica, Nissa, Tasya"},
  {name:"Lego",cat:"Mainan",how:"Meja Produksi: Kayu Gelondong + Kaleng Cat",tip:""},
  {name:"Lele Crispy",cat:"Makanan",how:"Beli di FFC area 5",tip:""},
  {name:"Lele Goreng",cat:"Makanan",how:"Masak sendiri",tip:""},
  {name:"Lem",cat:"Material",how:"Beli di Toko Bangunan area 2",tip:""},
  {name:"Liontin",availDays:["Selasa", "Jumat"],cat:"Perhiasan",how:"Beli di toko Pak Tatang",tip:""},
  {name:"Lipstik",availDays:["Senin", "Rabu", "Jumat"],cat:"Kecantikan",how:"Beli di toko Pak Tatang",tip:""},
  {name:"Lobster",cat:"Ikan",how:"Mancing di pantai",tip:"Luck 2"},
  {name:"Lobster Saus Padang",cat:"Makanan",how:"Beli di Joysteak area 4",tip:""},
  // M
  {name:"Mainan Anak",cat:"Mainan",how:"Mulung",tip:""},
  {name:"Mainan Kekinian",cat:"Mainan",how:"Beli di toko mainan atau Omegamart",tip:""},
  {name:"Mainan Tradisional",cat:"Mainan",how:"Meja Produksi",tip:""},
  {name:"Majalah Wanita",availDays:["Selasa", "Kamis", "Sabtu"],cat:"Buku",how:"Beli di toko Pak Tatang",tip:""},
  {name:"Mangga",cat:"Buah",how:"Media Pembenihan atau beli di pasar",tip:""},
  {name:"Masker",availDays:["Senin", "Rabu", "Jumat"],cat:"Kecantikan",how:"Beli di toko Pak Tatang atau Omegamart",tip:""},
  {name:"Mie Ayam",cat:"Makanan",how:"Beli di Warung Mas Kumis area 2",tip:""},
  {name:"Mie Goreng",cat:"Makanan",how:"Masak sendiri",tip:""},
  {name:"Minuman Energi",cat:"Minuman",how:"Beli di Indomarket atau Omegamart",tip:""},
  {name:"Mobil-mobilan",cat:"Mainan",how:"Meja Produksi",tip:""},
  {name:"Mur Baut",cat:"Material",how:"Dari kucing atau mulung",tip:""},
  {name:"Mutiara",cat:"Perhiasan",how:"Mancing di area 3 (langka)",tip:""},
  // N
  {name:"Nangka",cat:"Buah",how:"Tanam atau beli di pasar",tip:"Juga bisa digunakan sebagai bahan Getah Pohon"},
  {name:"Nasi Goreng",cat:"Makanan",how:"Masak sendiri",tip:""},
  {name:"Nata de Coco",cat:"Makanan",how:"Beli di Omegamart",tip:""},
  {name:"Novel",cat:"Buku",how:"Beli di Gramedia area 5",tip:""},
  {name:"Nugget Ayam",cat:"Makanan",how:"Beli di Mr. Ronald area 5",tip:""},
  // O
  {name:"Obat Herbal",cat:"Kesehatan",how:"Beli di toko obat atau mulung",tip:""},
  {name:"Obat Nyamuk Bakar",cat:"Perabotan",how:"Beli di Indomarket atau Omegamart",tip:""},
  {name:"Obeng",cat:"Peralatan",how:"Mulung",tip:""},
  {name:"Oseng Jantung Pisang",cat:"Makanan",how:"Masak sendiri: Jantung Pisang + bumbu",tip:"Salah satu hadiah Milah +8"},
  // P
  {name:"Paku",cat:"Material",how:"Mulung",tip:""},
  {name:"Pancingan",cat:"Peralatan",how:"Meja Produksi atau dari Pak Soleh",tip:""},
  {name:"Papan Kayu",cat:"Material",how:"Meja Produksi",tip:""},
  {name:"Parfum",availDays:["Senin", "Rabu", "Jumat"],cat:"Kecantikan",how:"Beli di toko Pak Tatang",tip:""},
  {name:"Parsel Hadiah",cat:"Hadiah",how:"Beli di Omegamart saat event atau toko tertentu",tip:"Disukai SEMUA karakter!"},
  {name:"Patung Kuno",cat:"Barang Kuno",how:"Mulung",tip:""},
  {name:"Pecahan Keramik",cat:"Material",how:"Mulung",tip:""},
  {name:"Pelampung",cat:"Material",how:"Meja Produksi",tip:""},
  {name:"Pelumas",cat:"Material",how:"Meja Produksi atau mulung",tip:""},
  {name:"Pen Fountain",cat:"Alat Tulis",how:"Beli di toko alat tulis premium atau mulung kampus",tip:"Hadiah +8 beberapa heroine"},
  {name:"Pensil",cat:"Alat Tulis",how:"Beli di toko alat tulis area 3",tip:""},
  {name:"Pensil Warna",cat:"Alat Tulis",how:"Beli di toko alat tulis area 3",tip:""},
  {name:"Perangkap Tikus",cat:"Peralatan",how:"Mulung atau beli",tip:""},
  {name:"Permen Lolipop",cat:"Makanan",how:"Beli di Indomarket atau Omegamart",tip:""},
  {name:"Pilar Marmer",cat:"Barang Kuno",how:"Mulung di area tertentu",tip:""},
  {name:"Pipa Logam",cat:"Material",how:"Mulung atau crafting",tip:"Bahan Lampu Minyak"},
  {name:"Piring Kuno",cat:"Barang Kuno",how:"Mulung",tip:"Disukai SEMUA karakter sebagai +8"},
  {name:"Pisau Dapur",cat:"Peralatan",how:"Mulung",tip:""},
  {name:"Plat Baja",cat:"Material",how:"Meja Produksi: Batang Logam + Briket Arang atau beli di Toko Bangunan",tip:""},
  {name:"Puding Coklat",cat:"Makanan",how:"Beli di Omegamart",tip:""},
  // R
  {name:"Radio",cat:"Elektronik",how:"Mulung",tip:""},
  {name:"Ranting Daun",cat:"Material",how:"Mulung",tip:"Bahan banyak crafting"},
  {name:"Ranting Pohon",cat:"Material",how:"Mulung",tip:""},
  {name:"Rol Film",cat:"Barang Unik",how:"Mulung atau toko tertentu",tip:"Salah satu hadiah Milah +8"},
  {name:"Roti",cat:"Makanan",how:"Beli di toko Pak Tatang",tip:""},
  {name:"Roti Bakar",cat:"Makanan",how:"Beli di Omegamart atau masak",tip:""},
  {name:"Rotan",cat:"Material",how:"Mancing harta karun Sungai Bojong Lima",tip:"Bahan beberapa crafting khusus"},
  // S
  {name:"Sabun Colek",cat:"Perabotan",how:"Abu Gosok",tip:""},
  {name:"Sak Semen",cat:"Material",how:"Toko Bangunan area 2",tip:""},
  {name:"Salad Buah",cat:"Makanan",how:"Masak sendiri",tip:""},
  {name:"Salmon Bakar",cat:"Makanan",how:"Beli di Joysteak area 4 atau masak",tip:""},
  {name:"Sari Buah",cat:"Minuman",how:"Beli di Indomarket atau Omegamart",tip:""},
  {name:"Sapu",cat:"Perabotan",how:"Meja Produksi: Ranting + Serat Tanaman",tip:""},
  {name:"Sate",cat:"Makanan",how:"Beli di Warung Mas Kumis area 2 atau masak",tip:""},
  {name:"Sawi",cat:"Sayuran",how:"Tanam atau Media Pembenihan",tip:""},
  {name:"Seblak",cat:"Makanan",how:"Beli di warung atau masak sendiri",tip:""},
  {name:"Selendang Sutera",cat:"Crafting Khusus",how:"Meja Produksi: Saputangan x2 + Benang Jahit",tip:"Quest Asih"},
  {name:"Semangka",cat:"Buah",how:"Tanam atau beli di pasar",tip:""},
  {name:"Sendok",cat:"Perabotan",how:"Mulung",tip:""},
  {name:"Sendok Bengkok",cat:"Material",how:"Mulung",tip:""},
  {name:"Sepatu",availDays:["Rabu", "Sabtu"],cat:"Pakaian",how:"Beli di toko Pak Tatang (Rabu, Sabtu)",tip:""},
  {name:"Sepatu Kulit",cat:"Pakaian",how:"Mulung",tip:""},
  {name:"Sepatu Roda",cat:"Mainan",how:"Mulung",tip:""},
  {name:"Serpihan Logam",cat:"Material",how:"Mulung",tip:"Bahan Batang Logam"},
  {name:"Serpihan Serat",cat:"Material",how:"Mulung",tip:"Bahan berbagai crafting"},
  {name:"Setrika",cat:"Perabotan",how:"Mulung",tip:""},
  {name:"Singkong Goreng",cat:"Makanan",how:"Masak sendiri atau beli di warung",tip:""},
  {name:"Sirup",cat:"Minuman",how:"Beli di Indomarket atau Omegamart",tip:""},
  {name:"Sisir",cat:"Perabotan",how:"Beli di Omegamart atau mulung",tip:""},
  {name:"Siput Emas",cat:"Berharga",how:"Mulung (sangat langka!)",tip:"Disukai SEMUA karakter sebagai +8"},
  {name:"Steak Sirloin",cat:"Makanan",how:"Beli di Joysteak area 4 atau masak",tip:""},
  {name:"Steak T-bone",cat:"Makanan",how:"Beli di Joysteak area 4 atau masak",tip:""},
  {name:"Susu Kotak",cat:"Minuman",how:"Beli di Indomarket atau Omegamart",tip:""},
  // T
  {name:"Tablet",cat:"Elektronik",how:"Mulung",tip:""},
  {name:"Tahu Bulat",cat:"Makanan",how:"Beli di Warung Ganormal area 4",tip:""},
  {name:"Tali Tambang",cat:"Material",how:"Meja Produksi",tip:""},
  {name:"Tanah Liat",cat:"Material",how:"Mulung",tip:""},
  {name:"Tas Tangan",availDays:["Selasa", "Kamis"],cat:"Aksesoris",how:"Beli di toko Pak Tatang",tip:""},
  {name:"Teh Botol",cat:"Minuman",how:"Beli di Indomarket atau Omegamart",tip:""},
  {name:"Teh Herbal",cat:"Minuman",how:"Meja Produksi: Ranting + Kayu Manis + Eceng Gondok + Rumput Kering",tip:"Beberapa karakter menyukainya"},
  {name:"Teko",cat:"Perabotan",how:"Mulung",tip:""},
  {name:"Teka-Teki Silang",cat:"Buku",how:"Beli di Gramedia area 5",tip:""},
  {name:"Telur Kejutan",cat:"Mainan",how:"Beli di toko mainan atau Omegamart",tip:""},
  {name:"Tempe Goreng",cat:"Makanan",how:"Masak sendiri",tip:""},
  {name:"Terong",cat:"Sayuran",how:"Tanam atau beli di Omegamart",tip:""},
  {name:"Thinner",cat:"Material",how:"Meja Produksi",tip:"Bahan Bola Api & Karet Olahan"},
  {name:"Tiket Lotre",cat:"Lainnya",how:"Beli di Omegamart",tip:""},
  {name:"Tomat",cat:"Sayuran",how:"Tanam atau beli di Omegamart",tip:""},
  {name:"Topi",availDays:["Selasa"],cat:"Pakaian",how:"Beli di toko Pak Tatang (Selasa)",tip:""},
  {name:"Topi Jerami",cat:"Pakaian",how:"Mulung",tip:""},
  {name:"Toples Kaca",cat:"Perabotan",how:"Mulung atau Tungku Pelebur",tip:""},
  {name:"Tube Lem",cat:"Material",how:"Meja Produksi: Getah Pohon + Air",tip:""},
  {name:"Tumpeng",cat:"Makanan Khusus",how:"Meja Produksi: Nasi + Daging Ayam + Daging + Cabai + Udang Sungai",tip:"Quest event"},
  {name:"Tupperware",cat:"Perabotan",how:"Beli di Omegamart atau mulung",tip:"Hadiah Isma +8"},
  {name:"Tutut",cat:"Lainnya",how:"Mulung di area sawah",tip:""},
  // U
  {name:"Udang Sungai",cat:"Ikan",how:"Mancing di Sungai Bojong Lima area 6",tip:"Luck 1"},
  // V
  {name:"Vas Bunga",cat:"Perabotan",how:"Mulung",tip:""},
  // W
  {name:"Wajan",cat:"Perabotan",how:"Beli di toko perabotan",tip:""},
  {name:"Walkie Talkie",cat:"Elektronik",how:"Mulung atau toko tertentu",tip:"Salah satu hadiah Milah +8"},
];

/* ── FISH DATA (for Mancing tab) ── */
const fishData = [
  // Luck 0 — Sangat Umum
  {name:"Ikan Mas",luck:0,loc:"Sungai",time:"Kapan saja",tip:"Sangat umum, tersedia kapan saja."},
  {name:"Ikan Tawes",luck:0,loc:"Sungai",time:"Kapan saja",tip:"Sangat umum sepanjang hari."},
  {name:"Ikan Nila",luck:0,loc:"Sungai",time:"Kapan saja",tip:"Mudah didapat sepanjang hari."},
  {name:"Kecebong",luck:0,loc:"Sungai",time:"Kapan saja",tip:"Sangat umum, cocok untuk pemula."},
  {name:"Kodok",luck:0,loc:"Sungai",time:"Kapan saja",tip:"Sangat umum, tidak butuh syarat khusus."},
  {name:"Ikan Bilis",luck:0,loc:"Sungai",time:"Kapan saja",tip:"Sangat umum di semua kondisi."},
  {name:"Tutut",luck:0,loc:"Sungai",time:"Pagi, Malam",tip:"Hindari siang hari untuk peluang lebih baik."},
  // Luck 1 — Umum
  {name:"Ikan Gurami",luck:1,loc:"Sungai",time:"Kapan saja",tip:"Tersedia kapan saja, cukup umum."},
  {name:"Ikan Patin",luck:1,loc:"Sungai",time:"Kapan saja",tip:"Tersedia kapan saja."},
  {name:"Ikan Mujair",luck:1,loc:"Danau",time:"Kapan saja",tip:"Umum di area danau."},
  {name:"Ikan Pelangi",luck:1,loc:"Kolam",time:"Kapan saja",tip:"⭐ Disukai HAMPIR SEMUA karakter sebagai +5! Prioritas utama dicari."},
  {name:"Ikan Diskus",luck:1,loc:"Kolam",time:"Kapan saja",tip:"Umum, mudah dikoleksi untuk hadiah."},
  {name:"Ikan Betok",luck:1,loc:"Kolam",time:"Kapan saja",tip:"Umum di kolam Area 3."},
  {name:"Ikan Gupi",luck:1,loc:"Selokan",time:"Kapan saja",tip:"Umum ditemukan di selokan."},
  {name:"Ikan Sapu-sapu",luck:1,loc:"Selokan",time:"Kapan saja",tip:"Umum, sering tertangkap tidak sengaja."},
  {name:"Yuyu / Kepiting Sungai",luck:1,loc:"Selokan",time:"Kapan saja",tip:"Umum di selokan."},
  {name:"Udang Sungai",luck:1,loc:"Sungai Bojong Lima",time:"Kapan saja",tip:"Area 6 — Sungai Bojong Lima."},
  // Luck 2 — Cukup Langka
  {name:"Ikan Bala-bala",luck:2,loc:"Sungai",time:"Kapan saja",tip:"Cukup langka tapi tidak terikat waktu."},
  {name:"Ikan Belida",luck:2,loc:"Sungai",time:"Siang, Sore",tip:"Jendela waktu siang-sore lebih menjanjikan."},
  {name:"Ikan Piranha",luck:2,loc:"Sungai",time:"Sore, Malam",tip:"Aktif menjelang malam."},
  {name:"Ikan Gabus",luck:2,loc:"Selokan",time:"Kapan saja",tip:"Cukup langka di area selokan."},
  {name:"Ikan Malaikat",luck:2,loc:"Kolam",time:"Kapan saja",tip:"⭐ Favorit +8 BANYAK heroine termasuk Isma!"},
  {name:"Ikan Cupang",luck:2,loc:"Kolam",time:"Kapan saja",tip:"Cukup langka, sering di kolam depan masjid."},
  {name:"Ikan Koi",luck:2,loc:"Danau",time:"Kapan saja",tip:"Cukup langka, biasa di kolam hias atau danau."},
  {name:"Ikan Mas Koki",luck:2,loc:"Danau",time:"Kapan saja",tip:"Cukup langka, warna mencolok."},
  {name:"Lobster",luck:2,loc:"Pantai",time:"Kapan saja",tip:"Cukup langka, coba di area pantai."},
  {name:"Ikan Sidat",luck:2,loc:"Sungai",time:"Malam",tip:"Hanya muncul malam hari."},
  // Luck 3 — Langka
  {name:"Ikan Black Ghost",luck:3,loc:"Kolam",time:"Malam",tip:"Langka, area kolam khusus malam hari."},
  {name:"Ikan Arwana",luck:3,loc:"Danau",time:"Kapan saja",tip:"Langka, area danau yang lebih dalam."},
  {name:"Ikan Lohan",luck:3,loc:"Danau",time:"Kapan saja",tip:"Langka, butuh kesabaran ekstra."},
  {name:"Kura-kura",luck:3,loc:"Pantai",time:"Kapan saja",tip:"Langka, coba di area pantai berbatu."},
  {name:"Ikan Piranha (langka)",luck:3,loc:"Sungai",time:"Tengah Malam",tip:"Varian langka, muncul tengah malam."},
  // Luck 4 — Sangat Langka
  {name:"Ikan Ayam-Ayam",luck:4,loc:"Selokan",time:"Siang (11:00–15:00)",tip:"SANGAT LANGKA. Cuaca cerah meningkatkan peluang. Bisa juga di Kolam Area 4 tapi lebih kecil."},
  {name:"Ikan Ghostfish",luck:4,loc:"Sungai",time:"Tengah Malam",tip:"Sangat langka. Hanya muncul tengah malam. Hadiah +8 Milah & Suciasih."},
  {name:"Ikan Naga",luck:4,loc:"Sungai Bojong Lima",time:"Kapan saja",tip:"SANGAT LANGKA. Area 6 Sungai Bojong Lima."},
  {name:"Ikan Hantu",luck:4,loc:"Sungai",time:"Tengah Malam (22:00+)",tip:"Sangat langka, hanya muncul sangat malam. Ada kaitannya dengan quest."},
  {name:"Ikan Hantu Hitam",luck:4,loc:"Area Khusus",time:"Malam (22:00+)",tip:"Digunakan untuk mendapatkan Batu Mistis di HOTLIN HOTEL (quest Asih)."},
  {name:"Siput Emas / Keong Mas",luck:4,loc:"Danau",time:"Kapan saja",tip:"SANGAT LANGKA & SANGAT BERHARGA. Favorit +8 banyak heroine. Coba pakai umpan premium."},
];

/* ── RECIPES ── */
const recipes = [
  // Meja Produksi Lv.1
  {station:"Meja Produksi Lv.1", result:"Sapu", ing:["Ranting","Serat Tanaman"], alt:""},
  {station:"Meja Produksi Lv.1", result:"Keranjang", ing:["Serat Tanaman","Ranting"], alt:""},
  {station:"Meja Produksi Lv.1", result:"Kipas", ing:["Bambu","Kertas Bekas"], alt:""},
  {station:"Meja Produksi Lv.1", result:"Kayu Kering", ing:["Ranting Daun"], alt:""},
  {station:"Meja Produksi Lv.1", result:"Mainan Tradisional", ing:["Tanah Liat","Kayu Kering","Benih Random"], alt:""},
  {station:"Meja Produksi Lv.1", result:"Lego / Balok Mainan", ing:["Kayu Gelondong","Kaleng Cat"], alt:""},
  {station:"Meja Produksi Lv.1", result:"Boneka Kain (Perca)", ing:["Benang Jahit","Kain","Serpihan Serat"], alt:""},
  {station:"Meja Produksi Lv.1", result:"Getah Pohon", ing:["Ranting Daun x2"], alt:"Atau 1 Nangka"},
  {station:"Meja Produksi Lv.1", result:"Tube Lem", ing:["Getah Pohon","Air"], alt:""},
  {station:"Meja Produksi Lv.1", result:"Tripleks", ing:["Tube Lem","Serpihan Logam"], alt:""},
  {station:"Meja Produksi Lv.1", result:"Bola Karet", ing:["Karet Gelang x2","Pelumas"], alt:""},
  {station:"Meja Produksi Lv.1", result:"Katapel", ing:["Ranting Pohon","Karet Gelang"], alt:""},
  {station:"Meja Produksi Lv.1", result:"Mobil-mobilan", ing:["Kayu Gelondong","Kawat","Mur Baut"], alt:""},
  {station:"Meja Produksi Lv.1", result:"Pancingan", ing:["Bambu","Kawat","Benang Jahit"], alt:""},
  {station:"Meja Produksi Lv.1", result:"Pelampung", ing:["Serpihan Serat","Bola Karet"], alt:""},
  {station:"Meja Produksi Lv.1", result:"Kain Perca", ing:["Kain","Benang Jahit"], alt:""},
  {station:"Meja Produksi Lv.1", result:"Tali Tambang", ing:["Serpihan Serat x3"], alt:""},
  {station:"Meja Produksi Lv.1", result:"Papan Kayu", ing:["Kayu Gelondong x2","Tube Lem"], alt:""},
  // Meja Produksi Lv.2
  {station:"Meja Produksi Lv.2", result:"Dinamo", ing:["Kabel","Kawat","Gir Mesin","Plat Baja","Pelumas"], alt:""},
  {station:"Meja Produksi Lv.2", result:"Bambu Olahan", ing:["Sapu","Kawat"], alt:"Atau Bambu + Kawat + Benang Jahit"},
  {station:"Meja Produksi Lv.2", result:"Laptop Rakitan", ing:["Dinamo","Kaca Olahan","Papan Kayu","Kabel x2"], alt:""},
  // Tungku Pelebur
  {station:"Tungku Pelebur", result:"Batang Logam", ing:["Serpihan Logam","Briket Arang"], alt:""},
  {station:"Tungku Pelebur", result:"Kaca Olahan", ing:["Botol Beling","Pasir"], alt:""},
  {station:"Tungku Pelebur", result:"Karet Olahan", ing:["Karet Gelang","Thinner"], alt:""},
  {station:"Tungku Pelebur", result:"Plat Baja", ing:["Batang Logam","Briket Arang"], alt:""},
  // Crafting Khusus (Quest Asih/Joko)
  {station:"Crafting Khusus (Quest)", result:"Air Doa", ing:["Ikan Malaikat","Cangkir","Kuas"], alt:"Untuk quest Asih"},
  {station:"Crafting Khusus (Quest)", result:"Batu Bulan", ing:["Batu","Kerikil Warna-warni","Kristal Warna-warni"], alt:"Tungku Pelebur — Quest Asih"},
  {station:"Crafting Khusus (Quest)", result:"Batu Nisan", ing:["Batu Marmer","Batu Hias","Kerikil Warna-warni"], alt:""},
  {station:"Crafting Khusus (Quest)", result:"Bola Api", ing:["Rotan x2","Tumpukan Jerami","Thinner"], alt:""},
  {station:"Crafting Khusus (Quest)", result:"Gamelan", ing:["Batang Logam","Kayu Gelondong x2","Kristal Warna-warni"], alt:"Hadiah Milah +8"},
  {station:"Crafting Khusus (Quest)", result:"Jelangkung", ing:["Bambu","Rotan x2","Batok Kelapa"], alt:""},
  {station:"Crafting Khusus (Quest)", result:"Kemenyan", ing:["Briket Arang","Kayu Manis","Serpihan Serat","Getah Pohon"], alt:"Tungku Pelebur"},
  {station:"Crafting Khusus (Quest)", result:"Kembang Tujuh Rupa", ing:["Bunga x3","Jantung Pisang"], alt:""},
  {station:"Crafting Khusus (Quest)", result:"Lampu Minyak", ing:["Plat Baja","Batok Kelapa","Pipa Logam","Kaca"], alt:"Tungku Pelebur"},
  {station:"Crafting Khusus (Quest)", result:"Selendang Sutera", ing:["Saputangan x2","Benang Jahit"], alt:""},
  {station:"Crafting Khusus (Quest)", result:"Teh Herbal", ing:["Ranting","Kayu Manis","Eceng Gondok","Rumput Kering"], alt:""},
  {station:"Crafting Khusus (Quest)", result:"Tumpeng", ing:["Nasi","Daging Ayam","Daging","Cabai","Udang Sungai"], alt:"Quest event"},
];

/* ── JOBS ── */
const jobs = [
  {name:"Kepala Cabang",area:"4",loc:"Bank, Area 4",salary:72,hours:"08:00–21:00",skill:{k:5,f:3,c:5},costume:"Baju Jas Hitam",exp:"Sekdes & Penjaga Toko",desc:"Posisi bergengsi di bank area 4. Membutuhkan skill tinggi dan pengalaman sebelumnya."},
  {name:"Guru",area:"3",loc:"Tempat Les, Area 3",salary:70,hours:"07:00–20:00",skill:{k:5,f:3,c:5},costume:"Jas Abu-abu",exp:"Guru Les",desc:"Mengajar di tempat les area 3. Membutuhkan kecerdasan dan komunikasi tinggi."},
  {name:"Kurir Kilat",area:"4",loc:"Area 4",salary:70,hours:"07:00–00:00",skill:{k:5,f:5,c:3},costume:"Baju Training Kuning",exp:"Penjaga Toko & Ojek Online",desc:"Mengantarkan paket dengan cepat. Jam kerja panjang, membutuhkan fisik prima."},
  {name:"Sopir Travel",area:"4",loc:"Area 4",salary:66,hours:"07:00–00:00",skill:{k:3,f:5,c:4},costume:"Baju Koko Hitam",exp:"Ojek Online & Sopir Taksi",desc:"Mengantar penumpang antar kota. Penghasilan cukup besar."},
  {name:"Youtuber",area:"3",loc:"Area 3",salary:65,hours:"06:00–00:00",skill:{k:5,f:3,c:5},costume:"Kostum Nge-prank",exp:"Tukang Service & Joki Game",desc:"Membuat konten video untuk internet. Jam kerja fleksibel namun butuh skill dan kreativitas tinggi."},
  {name:"Bos Catering",area:"4",loc:"Area 4",salary:65,hours:"06:00–22:30",skill:{k:3,f:5,c:4},costume:"Baju Koko Putih",exp:"Penjaga Warteg & Pedagang Pecel Lele",desc:"Mengelola usaha catering. Membutuhkan pengalaman memasak dan manajemen."},
  {name:"Sopir Bus",area:"3",loc:"Area 3",salary:65,hours:"06:00–00:00",skill:{k:3,f:5,c:3},costume:"Baju Batik",exp:"Sopir Taksi",desc:"Mengemudikan bus kota. Membutuhkan fisik kuat dan pengalaman berkendara."},
  {name:"Food Vlogger",area:"3",loc:"Area 3",salary:55,hours:"06:00–00:30",skill:{k:5,f:2,c:4},costume:"Baju Hawaii",exp:"Guru Les & Penjaga Warteg",desc:"Membuat konten kuliner. Penghasilan lumayan dengan jam kerja yang fleksibel."},
  {name:"Sekdes",area:"3",loc:"Balai Desa, Area 3",salary:52,hours:"06:00–20:00",skill:{k:5,f:2,c:3},costume:"Baju Rompi",exp:"Tukang Foto Copy",desc:"Sekretaris desa. Membantu kepala desa dalam administrasi."},
  {name:"Guru Les",area:"3",loc:"Tempat Les, Area 3",salary:38,hours:"07:00–19:00",skill:{k:3,f:1,c:3},costume:"Baju Putih Polos",exp:"—",desc:"Memberikan les privat kepada murid. Cocok untuk awal karier."},
  {name:"Sopir Taksi",area:"2",loc:"Area 2",salary:35,hours:"06:00–22:00",skill:{k:2,f:4,c:2},costume:"Baju Polo",exp:"Ojek Online",desc:"Mengantar penumpang di dalam kota. Penghasilan stabil."},
  {name:"Ojek Online",area:"1",loc:"Area 1",salary:30,hours:"06:00–22:00",skill:{k:2,f:3,c:1},costume:"Jaket Ojol",exp:"—",desc:"Pekerjaan pertama yang mudah didapat. Tidak membutuhkan pengalaman khusus."},
  {name:"Joki Game",area:"3",loc:"Warnet, Area 3",salary:28,hours:"08:00–22:00",skill:{k:2,f:1,c:3},costume:"—",exp:"—",desc:"Menaikkan ranking game orang lain. Cocok untuk yang suka bermain game."},
  {name:"Tukang Service",area:"2",loc:"Area 2",salary:25,hours:"08:00–19:00",skill:{k:1,f:2,c:2},costume:"—",exp:"—",desc:"Memperbaiki barang elektronik dan perabotan rusak."},
  {name:"Tukang Foto Copy",area:"2",loc:"Area 2",salary:18,hours:"07:00–20:00",skill:{k:3,f:1,c:2},costume:"—",exp:"—",desc:"Melayani fotokopi dan percetakan dokumen."},
  {name:"Pedagang Pecel Lele",area:"2",loc:"Warung, Area 2",salary:22,hours:"10:00–22:00",skill:{k:2,f:2,c:1},costume:"—",exp:"—",desc:"Berjualan pecel lele di warung pinggir jalan."},
  {name:"Penjaga Warteg",area:"2",loc:"Warteg, Area 2",salary:20,hours:"06:00–20:00",skill:{k:2,f:1,c:1},costume:"—",exp:"—",desc:"Melayani pelanggan di warteg."},
  {name:"Penjaga Toko",area:"1",loc:"Toko Pak Tatang, Area 1",salary:20,hours:"08:00–18:00",skill:{k:2,f:1,c:1},costume:"—",exp:"—",desc:"Membantu Pak Tatang menjaga kios."},
  {name:"Pedagang Cuanki",area:"1",loc:"Area 1",salary:15,hours:"07:00–21:00",skill:{k:2,f:1,c:0},costume:"—",exp:"—",desc:"Berjualan cuanki keliling."},
];

const days   = ["Senin","Selasa","Rabu","Kamis","Jumat","Sabtu","Minggu"];
const times  = ["Pagi","Siang","Sore","Malam"];
const tOrd   = [8,5,3,1];
const tLbl   = {8:"⭐ +8 Spesial",5:"💚 +5 Favorit",3:"💜 +3 Suka",1:"🩶 +1 Biasa"};
const tCls   = {8:"t8",5:"t5",3:"t3",1:"t1"};
const rCls   = {8:"rp8",5:"rp5",3:"rp3",1:"rp1"};
const rLbl   = {8:"⭐+8",5:"💚+5",3:"💜+3",1:"🩶+1"};
const lkLbl  = ["Luck 0","Luck 1","Luck 2","Luck 3","Luck 4"];
const stations = ["Semua","Meja Produksi Lv.1","Meja Produksi Lv.2","Tungku Pelebur","Crafting Khusus (Quest)"];

/* ── Item availability helper ── */
const everyDay = ["Senin","Selasa","Rabu","Kamis","Jumat","Sabtu","Minggu"];
function itemAvailDays(name) {
  const it = items.find(i => i.name === name);
  if (!it) return everyDay;
  if (it.availDays) return it.availDays;
  return everyDay; // mulung/omegamart/mancing = every day
}
function isItemAvailOn(name, day) {
  return itemAvailDays(name).includes(day);
}
